apiVersion: v1
kind: Service
metadata:
  name: sample-hackazon-service
  namespace: test
spec:
  selector:
    app: hackazon
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
