apiVersion: v1
kind: Service
metadata:
  name: sample-attacker
  namespace: istio-system
spec:
  selector:
    app: sample-attacker
  type: NodePort
  ports:
    - port: 80
      nodePort: 32500
      targetPort: 8443
      name: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-attacker-deployment
  namespace: istio-system
  labels:
    app: sample-attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-attacker
  template:
    metadata:
      labels:
        app: sample-attacker
    spec:
      containers:
      - name: sample-attacker
        image: talyradware/myrepo:latest
        ports:
        - containerPort: 8443