apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hackazon-gateway
  namespace: test
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "hackazon.kwaf-demo.test"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hackazon
  namespace: test
spec:
  hosts:
  - "hackazon.kwaf-demo.test"
  gateways:
  - hackazon-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: sample-hackazon-service.test.svc.cluster.local
