apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 9 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    runtime: failed to create new OS thread (have 10 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000062c00)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000062c00)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000055000, 0x8)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc0004aa180)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable, locked to thread]:
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017efc0, 0xc800000064, 0xc8)
    	/usr/local/go/src/regexp/syntax/compile.go:88 +0x1a7a
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f030, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f0a0, 0xc600000063, 0xc6)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f110, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f180, 0xc400000062, 0xc4)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f1f0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f260, 0xc200000061, 0xc2)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f2d0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f340, 0xc000000060, 0xc0)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f3b0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f420, 0xbe0000005f, 0xbe)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f490, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f500, 0xbc0000005e, 0xbc)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f570, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f5e0, 0xba0000005d, 0xba)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f650, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f6c0, 0xb80000005c, 0xb8)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f730, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f7a0, 0xb60000005b, 0xb6)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f810, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f880, 0xb40000005a, 0xb4)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f8f0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f960, 0xb200000059, 0xb2)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017f9d0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fa40, 0xb000000058, 0xb0)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fab0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fb20, 0xae00000057, 0xae)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fb90, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fc00, 0xac00000056, 0xac)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fc70, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fce0, 0xaa00000055, 0xaa)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fd50, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fdc0, 0xa800000054, 0xa8)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fe30, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017fea0, 0xa600000053, 0xa6)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017ff10, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc00017ff80, 0xa400000052, 0xa4)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186000, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186070, 0xa200000051, 0xa2)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001860e0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186150, 0xa000000050, 0xa0)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001861c0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186230, 0x9e0000004f, 0x9e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001862a0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186310, 0x9c0000004e, 0x9c)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186380, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001863f0, 0x9a0000004d, 0x9a)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186460, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001864d0, 0x980000004c, 0x98)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186540, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001865b0, 0x960000004b, 0x96)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186620, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186690, 0x940000004a, 0x94)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186700, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186770, 0x9200000049, 0x92)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001867e0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186850, 0x9000000048, 0x90)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001868c0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186930, 0x8e00000047, 0x8e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001869a0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186a10, 0x8c00000046, 0x8c)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186a80, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186af0, 0x8a00000045, 0x8a)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186b60, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186bd0, 0x8800000044, 0x20300000000088)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186c40, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186cb0, 0x8600000043, 0x86)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186d20, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186d90, 0x8400000042, 0x84)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186e00, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186e70, 0x8200000041, 0x82)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186ee0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186f50, 0x8000000040, 0x80)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000186fc0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187030, 0x7e0000003f, 0x7e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001870a0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187110, 0x7c0000003e, 0x7c)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187180, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001871f0, 0x7a0000003d, 0x7a)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187260, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001872d0, 0x780000003c, 0x78)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187340, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001873b0, 0x760000003b, 0x76)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187420, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187490, 0x740000003a, 0x74)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187500, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187570, 0x7200000039, 0x72)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001875e0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187650, 0x7000000038, 0x70)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001876c0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187730, 0x6e00000037, 0x6e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001877a0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187810, 0x6c00000036, 0x6c)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187880, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001878f0, 0x6a00000035, 0x6a)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187960, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc0001879d0, 0x6800000034, 0x68)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187a40, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187ab0, 0x6600000033, 0x66)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00079fc20, 0xc000187b20, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    ...additional frames elided...
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000088400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000088400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x0, 0xc000046000, 0x9)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0xc000046000, 0x2a6cc00)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.handoffp(0xc000046000)
    	/usr/local/go/src/runtime/proc.go:2001 +0x52
    runtime.stoplockedm()
    	/usr/local/go/src/runtime/proc.go:2075 +0xf7
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2611 +0x48c
    runtime.goschedImpl(0xc000000180)
    	/usr/local/go/src/runtime/proc.go:2860 +0xda
    runtime.gopreempt_m(0xc000000180)
    	/usr/local/go/src/runtime/proc.go:2888 +0x34
    runtime.newstack()
    	/usr/local/go/src/runtime/stack.go:1047 +0x1bc
    runtime.morestack()
    	/usr/local/go/src/runtime/asm_amd64.s:449 +0x8f
