apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 6 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    runtime: failed to create new OS thread (have 6 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000270800)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000270800)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x0, 0xc000046000, 0x4)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0xc000046000, 0x2a6cc00)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.handoffp(0xc000046000)
    	/usr/local/go/src/runtime/proc.go:2001 +0x52
    runtime.entersyscallblock_handoff()
    	/usr/local/go/src/runtime/proc.go:3213 +0x30
    runtime.systemstack(0x46c2f4)
    	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
    runtime.mstart()
    	/usr/local/go/src/runtime/proc.go:1116
    
    goroutine 1 [syscall, locked to thread]:
    runtime.notetsleepg(0x2a9eb78, 0xffffffffffffffff, 0xc000046000)
    	/usr/local/go/src/runtime/lock_futex.go:235 +0x34 fp=0xc000427fc8 sp=0xc000427f98 pc=0x40c454
    runtime.gcBgMarkStartWorkers()
    	/usr/local/go/src/runtime/mgc.go:1840 +0x90 fp=0xc000428008 sp=0xc000427fc8 pc=0x41d150
    runtime.gcStart(0x0, 0x0, 0x0)
    	/usr/local/go/src/runtime/mgc.go:1296 +0x1ca fp=0xc000428080 sp=0xc000428008 pc=0x41bc2a
    runtime.mallocgc(0x240, 0x19ce1a0, 0x515b8b0678290901, 0xc000495210)
    	/usr/local/go/src/runtime/malloc.go:1153 +0x470 fp=0xc000428120 sp=0xc000428080 pc=0x40da30
    runtime.newobject(...)
    	/usr/local/go/src/runtime/malloc.go:1195
    runtime.mapassign(0x18bc100, 0xc00047d830, 0xc000495210, 0xc000495210)
    	/usr/local/go/src/runtime/map.go:667 +0x28b fp=0xc0004281a0 sp=0xc000428120 pc=0x40fd2b
    reflect.mapassign(0x18bc100, 0xc00047d830, 0xc000495210, 0xc0004ac6c0)
    	/usr/local/go/src/runtime/map.go:1319 +0x3f fp=0xc0004281d0 sp=0xc0004281a0 pc=0x46795f
    reflect.Value.SetMapIndex(0x18bc100, 0xc0004a5ee0, 0x195, 0x1858200, 0xc000495210, 0x98, 0x19ce1a0, 0xc0004ac6c0, 0x199)
    	/usr/local/go/src/reflect/value.go:1706 +0x27c fp=0xc000428250 sp=0xc0004281d0 pc=0x4a08fc
    encoding/json.(*decodeState).object(0xc0004a08f0, 0x18bc100, 0xc0004a5ee0, 0x195, 0xc0004a0918, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:807 +0x8da fp=0xc0004284e0 sp=0xc000428250 pc=0x6eb01a
    encoding/json.(*decodeState).value(0xc0004a08f0, 0x18bc100, 0xc0004a5ee0, 0x195, 0x18bc100, 0xc0004a5ee0)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000428548 sp=0xc0004284e0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0004a08f0, 0x1815520, 0xc0004a5d40, 0x16, 0xc0004a0918, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc0004287d8 sp=0xc000428548 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0004a08f0, 0x1815520, 0xc0004a5d40, 0x16, 0xc000428888, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000428840 sp=0xc0004287d8 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0004a08f0, 0x1815520, 0xc0004a5d40, 0xc0004a0918, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc0004288c8 sp=0xc000428840 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003c47b5, 0x9e1, 0xb64b, 0x1815520, 0xc0004a5d40, 0x26, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc000428910 sp=0xc0004288c8 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc0003f8000, 0xc0003c47b5, 0x9e1, 0xb64b, 0x7fba4203bb00, 0xc0003f8000)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc000428c18 sp=0xc000428910 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0000be9a0, 0x19ce1a0, 0xc0003f8000, 0x199, 0xc0000be9c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc000428ea8 sp=0xc000428c18 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0000be9a0, 0x19ce1a0, 0xc0003f8000, 0x199, 0xc0004a5b00, 0x99)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000428f10 sp=0xc000428ea8 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0000be9a0, 0x18e59a0, 0xc00037bf08, 0x195, 0xc0000be9c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc0004291a0 sp=0xc000428f10 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0000be9a0, 0x18e59a0, 0xc00037bf08, 0x195, 0x18e59a0, 0xc00037bf08)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000429208 sp=0xc0004291a0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0000be9a0, 0x1815520, 0xc00037bd40, 0x16, 0xc0000be9c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc000429498 sp=0xc000429208 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0000be9a0, 0x1815520, 0xc00037bd40, 0x16, 0xc0000fb548, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000429500 sp=0xc000429498 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0000be9a0, 0x1815520, 0xc00037bd40, 0xc0000be9c8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc000429588 sp=0xc000429500 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003c0000, 0x9d38, 0xfe00, 0x1815520, 0xc00037bd40, 0x7fba4206f290, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc0004295d0 sp=0xc000429588 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc00037bb00, 0xc0003c0000, 0x9d38, 0xfe00, 0x7fba4203bb00, 0xc00037bb00)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc0004298d8 sp=0xc0004295d0 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0000be8f0, 0x1a89300, 0xc00037bb00, 0x16, 0xc0000be918, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc000429b68 sp=0xc0004298d8 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0000be8f0, 0x1a89300, 0xc00037bb00, 0x16, 0xc0000fbc18, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000429bd0 sp=0xc000429b68 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0000be8f0, 0x1a89300, 0xc00037bb00, 0xc0000be918, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc000429c58 sp=0xc000429bd0 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003c0000, 0x9d39, 0xfe00, 0x1a89300, 0xc00037bb00, 0x0, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc000429ca0 sp=0xc000429c58 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.Swagger20Schema(0xc000377b30, 0xc0000fbd68, 0x12e538a)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:82 +0xb8 fp=0xc000429d08 sp=0xc000429ca0 pc=0x12e3bb8
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:66
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.initResolutionCache(0xc000377a70, 0xc000377a40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:57 +0x35 fp=0xc000429d58 sp=0xc000429d08 pc=0x12dedb5
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.init.0()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:51 +0x25 fp=0xc000429d78 sp=0xc000429d58 pc=0x12ded25
    runtime.doInit(0x288d900)
    	/usr/local/go/src/runtime/proc.go:5646 +0x8a fp=0xc000429da8 sp=0xc000429d78 pc=0x446f8a
    runtime.doInit(0x2884b40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429dd8 sp=0xc000429da8 pc=0x446f57
    runtime.doInit(0x2883340)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429e08 sp=0xc000429dd8 pc=0x446f57
    runtime.doInit(0x287fd40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429e38 sp=0xc000429e08 pc=0x446f57
    runtime.doInit(0x287c780)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429e68 sp=0xc000429e38 pc=0x446f57
    runtime.doInit(0x287c740)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429e98 sp=0xc000429e68 pc=0x446f57
    runtime.doInit(0x287c700)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429ec8 sp=0xc000429e98 pc=0x446f57
    runtime.doInit(0x288ff40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429ef8 sp=0xc000429ec8 pc=0x446f57
    runtime.doInit(0x288c0e0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429f28 sp=0xc000429ef8 pc=0x446f57
    runtime.doInit(0x28926a0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429f58 sp=0xc000429f28 pc=0x446f57
    runtime.doInit(0x2882980)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429f88 sp=0xc000429f58 pc=0x446f57
    runtime.main()
    	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc000429fe0 sp=0xc000429f88 pc=0x439c05
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000429fe8 sp=0xc000429fe0 pc=0x46e061
    
    goroutine 6 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000500000)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000500000)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc00004b000, 0x5)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0xc000073f01)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc000001080)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    system_key.go:147: cannot determine seccomp compiler version in generateSystemKey: fork/exec /snap/snapd/15534/usr/lib/snapd/snap-seccomp: resource temporarily unavailable
