apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 10 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000188400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000188400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000057800, 0x9)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0xc000073f01)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc00008a480)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable, locked to thread]:
    regexp/syntax.(*parser).factor(0xc000181c20, 0xc0003117b0, 0x2, 0x2, 0x2, 0xc0003117b0, 0x1)
    	/usr/local/go/src/regexp/syntax/parse.go:399 +0x1616
    regexp/syntax.(*parser).collapse(0xc000181c20, 0xc000311790, 0x2, 0x2, 0x13, 0xffffffffffffffff)
    	/usr/local/go/src/regexp/syntax/parse.go:378 +0x427
    regexp/syntax.(*parser).factor(0xc000181c20, 0xc000311790, 0x2, 0x2, 0x2, 0xc000311790, 0x1)
    	/usr/local/go/src/regexp/syntax/parse.go:510 +0xc99
    regexp/syntax.(*parser).collapse(0xc000181c20, 0xc00019f730, 0x2, 0xa, 0xc000463a13, 0x7)
    	/usr/local/go/src/regexp/syntax/parse.go:378 +0x427
    regexp/syntax.(*parser).alternate(0xc000181c20, 0xc000463a01)
    	/usr/local/go/src/regexp/syntax/parse.go:333 +0x165
    regexp/syntax.(*parser).parseRightParen(0xc000181c20, 0xc00046e065, 0x82)
    	/usr/local/go/src/regexp/syntax/parse.go:1210 +0x76
    regexp/syntax.Parse(0xc00046e000, 0xe7, 0xc0004600d4, 0xe7, 0xc00046e000, 0xe7)
    	/usr/local/go/src/regexp/syntax/parse.go:742 +0x46f
    regexp.compile(0xc00046e000, 0xe7, 0xc0000000d4, 0xc00046e0b0, 0xc0007dfe28, 0xc0002381b0)
    	/usr/local/go/src/regexp/regexp.go:170 +0x5a
    regexp.Compile(...)
    	/usr/local/go/src/regexp/regexp.go:133
    regexp.MustCompile(0xc00046e000, 0xe7, 0xb0)
    	/usr/local/go/src/regexp/regexp.go:309 +0x4b
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.expression(0xc00061bdc0, 0x3, 0x3, 0xc00037ce60)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:115 +0x93
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.init()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:53 +0x8ee
    
    goroutine 6 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
