apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 9 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc0004d0c00)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc0004d0c00)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000055000, 0x8)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc0004da180)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable]:
    syscall.Syscall6(0x101, 0xffffffffffffff9c, 0xc0005cc020, 0x80000, 0x0, 0x0, 0x0, 0x3, 0x80000, 0x0)
    	/usr/local/go/src/syscall/asm_linux_amd64.s:41 +0x5
    syscall.openat(0xffffffffffffff9c, 0xc0002430e0, 0x1a, 0x80000, 0x10000c000000000, 0x466040, 0xc0009413f7, 0xc00004b000)
    	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:68 +0xbd
    syscall.Open(...)
    	/usr/local/go/src/syscall/syscall_linux.go:152
    os.openFileNolog(0xc0002430e0, 0x1a, 0x0, 0xc000000000, 0x4bfb0a, 0x4bebe8, 0x106)
    	/usr/local/go/src/os/file_unix.go:200 +0x8f
    os.OpenFile(0xc0002430e0, 0x1a, 0x0, 0x0, 0x40, 0xc0009414d0, 0x4e74c7)
    	/usr/local/go/src/os/file.go:327 +0x65
    os.Open(...)
    	/usr/local/go/src/os/file.go:307
    io/ioutil.ReadFile(0xc0002430e0, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/usr/local/go/src/io/ioutil/ioutil.go:53 +0x77
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.LoadFromFile(0xc0002430e0, 0x1a, 0x1, 0xc000298630, 0x1)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:371 +0x50
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*ClientConfigLoadingRules).Load(0xc0000d6640, 0xc00028d380, 0x30, 0x7fd00dd74d98)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:205 +0xb8f
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).createClientConfig(0xc0000d6690, 0x0, 0x0, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:69 +0xba
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).Namespace(0xc0000d6690, 0xc000941bb0, 0x14ff493, 0xc0005680b0, 0x1d29f00, 0xc000298650)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:131 +0x45
    k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions.(*clientConfig).Namespace(0xc000298650, 0x1d29f00, 0xc000298650, 0x32, 0x2a9f4a0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/client_config.go:61 +0x37
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*GetOptions).Complete(0xc00086a870, 0x1d441c0, 0xc0004111a0, 0xc0004462c0, 0xc000348780, 0x2, 0x6, 0x6e5000, 0xc000941cf8)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:199 +0xe8
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func1(0xc0004462c0, 0xc000348780, 0x2, 0x6)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:165 +0x7d
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004462c0, 0xc000348720, 0x6, 0x6, 0xc0004462c0, 0xc000348720)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f0b00, 0xc0000ba180, 0xc0000c8000, 0x8)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
    main.main()
    	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
    
    goroutine 34 [runnable]:
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bb7018, 0x12a05f200, 0xc00009cb40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:89
    created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96
