apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    system_key.go:147: cannot determine seccomp compiler version in generateSystemKey: fork/exec /snap/snapd/15534/usr/lib/snapd/snap-seccomp: resource temporarily unavailable
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 5 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc0002f0800)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc0002f0800)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x0, 0xc000046000, 0x4)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0xc000046000, 0x2a6cc00)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.handoffp(0xc000046000)
    	/usr/local/go/src/runtime/proc.go:2001 +0x52
    runtime.entersyscallblock_handoff()
    	/usr/local/go/src/runtime/proc.go:3213 +0x30
    runtime.systemstack(0x46c2f4)
    	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
    runtime.mstart()
    	/usr/local/go/src/runtime/proc.go:1116
    
    goroutine 1 [syscall, locked to thread]:
    runtime.notetsleepg(0x2a9eb78, 0xffffffffffffffff, 0xc000046000)
    	/usr/local/go/src/runtime/lock_futex.go:235 +0x34 fp=0xc000427908 sp=0xc0004278d8 pc=0x40c454
    runtime.gcBgMarkStartWorkers()
    	/usr/local/go/src/runtime/mgc.go:1840 +0x90 fp=0xc000427948 sp=0xc000427908 pc=0x41d150
    runtime.gcStart(0x0, 0x0, 0xc000000000)
    	/usr/local/go/src/runtime/mgc.go:1296 +0x1ca fp=0xc0004279c0 sp=0xc000427948 pc=0x41bc2a
    runtime.mallocgc(0x20, 0x0, 0x0, 0x15)
    	/usr/local/go/src/runtime/malloc.go:1153 +0x470 fp=0xc000427a60 sp=0xc0004279c0 pc=0x40da30
    runtime.slicebytetostring(0x0, 0xc0004a4500, 0x16, 0x0, 0x0)
    	/usr/local/go/src/runtime/string.go:110 +0x90 fp=0xc000427a90 sp=0xc000427a60 pc=0x453450
    bytes.(*Buffer).String(...)
    	/usr/local/go/src/bytes/buffer.go:65
    k8s.io/kubernetes/vendor/github.com/PuerkitoBio/urlesc.Escape(0xc0004aacf0, 0xc000377a10, 0x2000)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/PuerkitoBio/urlesc/urlesc.go:179 +0x169 fp=0xc000427af8 sp=0xc000427a90 pc=0x12dab89
    k8s.io/kubernetes/vendor/github.com/PuerkitoBio/purell.NormalizeURL(0xc0004aacf0, 0x207f, 0xc0004aacf0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/PuerkitoBio/purell/purell.go:183 +0xbf fp=0xc000427b40 sp=0xc000427af8 pc=0x12db01f
    k8s.io/kubernetes/vendor/github.com/go-openapi/jsonreference.(*Ref).parse(0xc000427bc8, 0xc000443fe0, 0x16, 0x4, 0xc0004b4bc8)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/jsonreference/reference.go:117 +0x65 fp=0xc000427b98 sp=0xc000427b40 pc=0x12dd8a5
    k8s.io/kubernetes/vendor/github.com/go-openapi/jsonreference.New(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/jsonreference/reference.go:45
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Ref).fromMap(0xc000427d48, 0xc00047dd70, 0xade0, 0x1811e60)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/ref.go:182 +0xe8 fp=0xc000427c50 sp=0xc000427b98 pc=0x12e0908
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc0004a9680, 0xc0003c9020, 0x36, 0xade0, 0x7fcd803703c0, 0xc0004a9680)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:569 +0x1bc fp=0xc000427f58 sp=0xc000427c50 pc=0x12e347c
    encoding/json.(*decodeState).object(0xc0004a09a0, 0x19ce1a0, 0xc0004a9680, 0x199, 0xc0004a09c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc0004281e8 sp=0xc000427f58 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0004a09a0, 0x19ce1a0, 0xc0004a9680, 0x199, 0xc0004bcb40, 0x99)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000428250 sp=0xc0004281e8 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0004a09a0, 0x18bc100, 0xc0004a8f20, 0x195, 0xc0004a09c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc0004284e0 sp=0xc000428250 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0004a09a0, 0x18bc100, 0xc0004a8f20, 0x195, 0x18bc100, 0xc0004a8f20)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000428548 sp=0xc0004284e0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0004a09a0, 0x1815520, 0xc0004a8d80, 0x16, 0xc0004a09c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc0004287d8 sp=0xc000428548 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0004a09a0, 0x1815520, 0xc0004a8d80, 0x16, 0xc000428888, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000428840 sp=0xc0004287d8 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0004a09a0, 0x1815520, 0xc0004a8d80, 0xc0004a09c8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc0004288c8 sp=0xc000428840 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003c87b5, 0x9e1, 0xb64b, 0x1815520, 0xc0004a8d80, 0x26, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc000428910 sp=0xc0004288c8 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc0003f8fc0, 0xc0003c87b5, 0x9e1, 0xb64b, 0x7fcd803703c0, 0xc0003f8fc0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc000428c18 sp=0xc000428910 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0000bea50, 0x19ce1a0, 0xc0003f8fc0, 0x199, 0xc0000bea78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc000428ea8 sp=0xc000428c18 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0000bea50, 0x19ce1a0, 0xc0003f8fc0, 0x199, 0xc0004a8b40, 0x99)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000428f10 sp=0xc000428ea8 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0000bea50, 0x18e59a0, 0xc00038af48, 0x195, 0xc0000bea78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc0004291a0 sp=0xc000428f10 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0000bea50, 0x18e59a0, 0xc00038af48, 0x195, 0x18e59a0, 0xc00038af48)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000429208 sp=0xc0004291a0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0000bea50, 0x1815520, 0xc00038ad80, 0x16, 0xc0000bea78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc000429498 sp=0xc000429208 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0000bea50, 0x1815520, 0xc00038ad80, 0x16, 0xc0000fb548, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000429500 sp=0xc000429498 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0000bea50, 0x1815520, 0xc00038ad80, 0xc0000bea78, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc000429588 sp=0xc000429500 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003c4000, 0x9d38, 0xfe00, 0x1815520, 0xc00038ad80, 0x7fcd803d0810, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc0004295d0 sp=0xc000429588 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc00038ab40, 0xc0003c4000, 0x9d38, 0xfe00, 0x7fcd803703c0, 0xc00038ab40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc0004298d8 sp=0xc0004295d0 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0000be9a0, 0x1a89300, 0xc00038ab40, 0x16, 0xc0000be9c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc000429b68 sp=0xc0004298d8 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0000be9a0, 0x1a89300, 0xc00038ab40, 0x16, 0xc0000fbc18, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc000429bd0 sp=0xc000429b68 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0000be9a0, 0x1a89300, 0xc00038ab40, 0xc0000be9c8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc000429c58 sp=0xc000429bd0 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003c4000, 0x9d39, 0xfe00, 0x1a89300, 0xc00038ab40, 0x0, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc000429ca0 sp=0xc000429c58 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.Swagger20Schema(0xc000377b30, 0xc0000fbd68, 0x12e538a)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:82 +0xb8 fp=0xc000429d08 sp=0xc000429ca0 pc=0x12e3bb8
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:66
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.initResolutionCache(0xc000377a70, 0xc000377a40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:57 +0x35 fp=0xc000429d58 sp=0xc000429d08 pc=0x12dedb5
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.init.0()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:51 +0x25 fp=0xc000429d78 sp=0xc000429d58 pc=0x12ded25
    runtime.doInit(0x288d900)
    	/usr/local/go/src/runtime/proc.go:5646 +0x8a fp=0xc000429da8 sp=0xc000429d78 pc=0x446f8a
    runtime.doInit(0x2884b40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429dd8 sp=0xc000429da8 pc=0x446f57
    runtime.doInit(0x2883340)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429e08 sp=0xc000429dd8 pc=0x446f57
    runtime.doInit(0x287fd40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429e38 sp=0xc000429e08 pc=0x446f57
    runtime.doInit(0x287c780)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429e68 sp=0xc000429e38 pc=0x446f57
    runtime.doInit(0x287c740)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429e98 sp=0xc000429e68 pc=0x446f57
    runtime.doInit(0x287c700)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429ec8 sp=0xc000429e98 pc=0x446f57
    runtime.doInit(0x288ff40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429ef8 sp=0xc000429ec8 pc=0x446f57
    runtime.doInit(0x288c0e0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429f28 sp=0xc000429ef8 pc=0x446f57
    runtime.doInit(0x28926a0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429f58 sp=0xc000429f28 pc=0x446f57
    runtime.doInit(0x2882980)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc000429f88 sp=0xc000429f58 pc=0x446f57
    runtime.main()
    	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc000429fe0 sp=0xc000429f88 pc=0x439c05
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000429fe8 sp=0xc000429fe0 pc=0x46e061
    
    goroutine 6 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
    system_key.go:147: cannot determine seccomp compiler version in generateSystemKey: fork/exec /snap/snapd/15534/usr/lib/snapd/snap-seccomp: resource temporarily unavailable
