apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    /bin/sh: 1: yq: not found
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    /bin/sh: 1: /bin/sh: 1: yq: not foundkubectl: not found
    
