apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 10 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000063800)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000063800)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000057800, 0x9)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc000381b00)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable]:
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.createDecoderOfNative(0xc0001282a0, 0x1d48960, 0xc000128300, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_native.go:116 +0x82
    k8s.io/kubernetes/vendor/github.com/json-iterator/go._createDecoderOfType(0xc0001282a0, 0x1d48960, 0xc000128300, 0xc0002fa1c8, 0xc0000a0ff0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:164 +0x15e
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.createDecoderOfType(0xc0001282a0, 0x1d48960, 0xc000128300, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:142 +0x10e
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.decoderOfType(0xc0001282a0, 0x1d48960, 0xc000128300, 0x1ac3348, 0x1)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:124 +0x7a
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.describeStruct(0xc000996f28, 0x1d48960, 0xc0001281b0, 0xc00002d3e2)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_extension.go:380 +0xf25
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.decoderOfStruct(0xc000996f28, 0x1d48960, 0xc0001281b0, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_decoder.go:14 +0xbd
    k8s.io/kubernetes/vendor/github.com/json-iterator/go._createDecoderOfType(0xc000996f28, 0x1d48960, 0xc0001281b0, 0xc0002fa1a8, 0xc0000a0ff0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:176 +0x485
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.createDecoderOfType(0xc000996f28, 0x1d48960, 0xc0001281b0, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:142 +0x10e
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.decoderOfType(0xc000996f28, 0x1d48960, 0xc0001281b0, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:124 +0x7a
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*frozenConfig).DecoderOf(0xc0001ac8c0, 0x1d48820, 0xc0001280f0, 0x1d48820, 0xc0001280f0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:114 +0x115
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*Iterator).ReadVal(0xc0004f4b40, 0x1969ae0, 0xc0000e4790)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:72 +0x1d0
    k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*frozenConfig).Unmarshal(0xc0001ac8c0, 0xc000122000, 0x15c2, 0x1800, 0x1969ae0, 0xc0000e4790, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/config.go:348 +0xb7
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode(0xc00010c1e0, 0xc000583000, 0x15a8, 0x17a8, 0xc0002c20f0, 0x1cf7bc0, 0xc00083bda0, 0x30, 0x7f6b198547d0, 0x7f6af29c9c58, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:264 +0x602
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode(0xc0004483c0, 0xc000583000, 0x15a8, 0x17a8, 0xc0002c20f0, 0x1cf7bc0, 0xc00083bda0, 0xc00000e670, 0x0, 0x0, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:136 +0xa9
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.Load(0xc000583000, 0x15a8, 0x17a8, 0x15a8, 0x17a8, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:416 +0x1aa
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.LoadFromFile(0xc00068a400, 0x1a, 0x1, 0xc00059e7e0, 0x1)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:375 +0x85
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*ClientConfigLoadingRules).Load(0xc0003d0f00, 0x30, 0x30, 0x7f6af2bfd260)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:205 +0xb8f
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).createClientConfig(0xc0003d0f50, 0x0, 0x0, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:69 +0xba
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).Namespace(0xc0003d0f50, 0xc00079fbb0, 0x14ff493, 0xc0001be6e0, 0x1d29f00, 0xc00059e820)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:131 +0x45
    k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions.(*clientConfig).Namespace(0xc00059e820, 0x1d29f00, 0xc00059e820, 0x32, 0x2a9f4a0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/client_config.go:61 +0x37
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*GetOptions).Complete(0xc000672870, 0x1d441c0, 0xc000576090, 0xc0004b42c0, 0xc00083bce0, 0x2, 0x6, 0x6e5000, 0xc00079fcf8)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:199 +0xe8
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func1(0xc0004b42c0, 0xc00083bce0, 0x2, 0x6)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:165 +0x7d
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004b42c0, 0xc00083bc80, 0x6, 0x6, 0xc0004b42c0, 0xc00083bc80)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f0b00, 0xc0000ba180, 0xc0000c8000, 0x8)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
    main.main()
    	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
    
    goroutine 24 [select]:
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1bb7018, 0x1cec100, 0xc0001a2000, 0x1, 0xc00009cb40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1bb7018, 0x12a05f200, 0x0, 0x1, 0xc00009cb40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bb7018, 0x12a05f200, 0xc00009cb40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
    created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96
