apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - name: apiPolicy
    operatorEmail: support@radware.com
    classifiers:
    - protectionId: nginx
      hostname: nginx.kwaf-demo.tes*
      id: nginx-sample
      path:
        operand: Prefix
        value: /
    - protectionId: hackazon
      hostname: 'hackazon.kwaf-demo.tes*'
      id: sample-hackazon      
      path:
        operand: Prefix
        value: /
    - protectionId: bwapp
      hostname: 'bwapp.kwaf-demo.tes*'
      id: bwapp-sample
      path:
        operand: Prefix
        value: /
    - protectionId: httpbin
      hostname: 'httpbin.kwaf-demo.tes*'
      id: httpbin-sample
      path:
        operand: Prefix
        value: /
    protections:
    - id: nginx
      expressions:
        opMode: Active
      signatures:
        opMode: Active
    - id: hackazon
      signatures:
        opMode: Active
      expressions:
        opMode: Active
    - id: httpbin
      signatures:
        opMode: Active
      expressions:
        opMode: Active
    - id: bwapp
      signatures:
        opMode: Active
      expressions:
        opMode: Active
