apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 10 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc0002f1800)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc0002f1800)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000057800, 0x9)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc00035c900)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable]:
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).scalar(0xc000680d20, 0xc0000dc4d0, 0x1897a80, 0xc000890080, 0x194, 0x1897a80)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:435 +0x15e9
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000680d20, 0xc0000dc4d0, 0x1897a80, 0xc000890080, 0x194, 0x194)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:370 +0x14f
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).mapping(0xc000680d20, 0xc0000dc2a0, 0x1897a80, 0xc000890030, 0x194, 0x1897a80)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:667 +0x37b
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000680d20, 0xc0000dc2a0, 0x1897a80, 0xc000890030, 0x194, 0x194)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:372 +0x1b6
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).mapping(0xc000680d20, 0xc0000dc150, 0x1897a80, 0xc000890000, 0x194, 0x1897a80)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:676 +0x479
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000680d20, 0xc0000dc150, 0x1897a80, 0xc000890000, 0x194, 0x194)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:372 +0x1b6
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).sequence(0xc000680d20, 0xc0000dc0e0, 0x1897a80, 0xc0007f8000, 0x194, 0x1897a80)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:609 +0x267
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000680d20, 0xc0000dc0e0, 0x1897a80, 0xc0007f8000, 0x194, 0x194)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:374 +0x18a
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).mapping(0xc000680d20, 0xc00039bf10, 0x1897a80, 0xc0007cbf10, 0x194, 0x1897a80)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:676 +0x479
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000680d20, 0xc00039bf10, 0x1897a80, 0xc0007cbf10, 0x194, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:372 +0x1b6
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).document(0xc000680d20, 0xc00039bea0, 0x1897a80, 0xc0007cbf10, 0x194, 0x8c3567)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:384 +0x7c
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.(*decoder).unmarshal(0xc000680d20, 0xc00039bea0, 0x1897a80, 0xc0007cbf10, 0x194, 0x194)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/decode.go:360 +0x250
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.unmarshal(0xc00094f000, 0x15a8, 0x17a8, 0x17fac60, 0xc0007cbf10, 0x1897a00, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/yaml.go:148 +0x33d
    k8s.io/kubernetes/vendor/gopkg.in/yaml%2ev2.Unmarshal(0xc00094f000, 0x15a8, 0x17a8, 0x17fac60, 0xc0007cbf10, 0x7fc601bc45f0, 0xa70)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gopkg.in/yaml.v2/yaml.go:81 +0x58
    k8s.io/kubernetes/vendor/sigs.k8s.io/yaml.yamlToJSON(0xc00094f000, 0x15a8, 0x17a8, 0x0, 0x1bb6660, 0x7fc6288200d4, 0x200000001, 0xc000a1f0d0, 0x44f2e5, 0xc0003a1500)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/sigs.k8s.io/yaml/yaml.go:124 +0x73
    k8s.io/kubernetes/vendor/sigs.k8s.io/yaml.YAMLToJSON(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/sigs.k8s.io/yaml/yaml.go:112
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode(0xc0001841e0, 0xc00094f000, 0x15a8, 0x17a8, 0xc00002aa50, 0x1cf7bc0, 0xc000680cc0, 0x30, 0x7fc628822108, 0x7fc601b68230, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:212 +0x109d
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode(0xc0003a43c0, 0xc00094f000, 0x15a8, 0x17a8, 0xc00002aa50, 0x1cf7bc0, 0xc000680cc0, 0xc000300a28, 0x0, 0x0, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:136 +0xa9
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.Load(0xc00094f000, 0x15a8, 0x17a8, 0x15a8, 0x17a8, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:416 +0x1aa
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.LoadFromFile(0xc0008898a0, 0x1a, 0x1, 0xc0007cbed0, 0x1)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:375 +0x85
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*ClientConfigLoadingRules).Load(0xc00060f7c0, 0x30, 0x30, 0x7fc601ba9030)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:205 +0xb8f
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).createClientConfig(0xc00060f810, 0x0, 0x0, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:69 +0xba
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).Namespace(0xc00060f810, 0xc000a1fbb0, 0x14ff493, 0xc0001eca50, 0x1d29f00, 0xc0007cbef0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:131 +0x45
    k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions.(*clientConfig).Namespace(0xc0007cbef0, 0x1d29f00, 0xc0007cbef0, 0x32, 0x2a9f4a0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/client_config.go:61 +0x37
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*GetOptions).Complete(0xc000640b40, 0x1d441c0, 0xc000791d10, 0xc000374580, 0xc000680c00, 0x2, 0x6, 0x6e5000, 0xc000a1fcf8)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:199 +0xe8
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func1(0xc000374580, 0xc000680c00, 0x2, 0x6)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:165 +0x7d
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000374580, 0xc000680ba0, 0x6, 0x6, 0xc000374580, 0xc000680ba0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000cab00, 0xc00003c240, 0xc00003a080, 0x8)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
    main.main()
    	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d
    
    goroutine 6 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
    
    goroutine 9 [select]:
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1bb7018, 0x1cec100, 0xc00013c000, 0x1, 0xc000088b40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1bb7018, 0x12a05f200, 0x0, 0x1, 0xc000088b40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bb7018, 0x12a05f200, 0xc000088b40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
    created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96
