apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 6 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000063000)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000063000)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x0, 0xc000046000, 0x5)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0xc000046000, 0x2a6cc00)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.handoffp(0xc000046000)
    	/usr/local/go/src/runtime/proc.go:2001 +0x52
    runtime.entersyscallblock_handoff()
    	/usr/local/go/src/runtime/proc.go:3213 +0x30
    runtime.systemstack(0x46c2f4)
    	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
    runtime.mstart()
    	/usr/local/go/src/runtime/proc.go:1116
    
    goroutine 1 [syscall, locked to thread]:
    runtime.notetsleepg(0x2a9eb78, 0xffffffffffffffff, 0xc000048800)
    	/usr/local/go/src/runtime/lock_futex.go:235 +0x34 fp=0xc00043d580 sp=0xc00043d550 pc=0x40c454
    runtime.gcBgMarkStartWorkers()
    	/usr/local/go/src/runtime/mgc.go:1840 +0x90 fp=0xc00043d5c0 sp=0xc00043d580 pc=0x41d150
    runtime.gcStart(0x0, 0x0, 0x0)
    	/usr/local/go/src/runtime/mgc.go:1296 +0x1ca fp=0xc00043d638 sp=0xc00043d5c0 pc=0x41bc2a
    runtime.mallocgc(0x20, 0x196e440, 0x6e8d01, 0xc0004b56d8)
    	/usr/local/go/src/runtime/malloc.go:1153 +0x470 fp=0xc00043d6d8 sp=0xc00043d638 pc=0x40da30
    runtime.newobject(0x196e440, 0x17)
    	/usr/local/go/src/runtime/malloc.go:1195 +0x38 fp=0xc00043d708 sp=0xc00043d6d8 pc=0x40e298
    reflect.MakeSlice(0x1d4e220, 0x181c100, 0x0, 0x4, 0x181c100, 0x0, 0x0)
    	/usr/local/go/src/reflect/value.go:2299 +0x85 fp=0xc00043d738 sp=0xc00043d708 pc=0x4a28a5
    encoding/json.(*decodeState).array(0xc0004b56b0, 0x181c100, 0xc0004c2c48, 0x197, 0xc0004b56d8, 0x5b)
    	/usr/local/go/src/encoding/json/decode.go:547 +0x716 fp=0xc00043d820 sp=0xc00043d738 pc=0x6ea196
    encoding/json.(*decodeState).value(0xc0004b56b0, 0x181c100, 0xc0004c2c48, 0x197, 0x181c100, 0xc0004c2c48)
    	/usr/local/go/src/encoding/json/decode.go:360 +0x105 fp=0xc00043d888 sp=0xc00043d820 pc=0x6e90e5
    encoding/json.(*decodeState).object(0xc0004b56b0, 0x1815520, 0xc0004c2b40, 0x16, 0xc0004b56d8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00043db18 sp=0xc00043d888 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0004b56b0, 0x1815520, 0xc0004c2b40, 0x16, 0xc00043dbc8, 0x6fa34b)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00043db80 sp=0xc00043db18 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0004b56b0, 0x1815520, 0xc0004c2b40, 0xc0004b56d8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00043dc08 sp=0xc00043db80 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003dabd6, 0xc9, 0xb22a, 0x1815520, 0xc0004c2b40, 0x26, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00043dc50 sp=0xc00043dc08 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc0004c06c0, 0xc0003dabd6, 0xc9, 0xb22a, 0x7f25a5ef6680, 0xc0004c06c0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc00043df58 sp=0xc00043dc50 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0004b4a50, 0x19ce1a0, 0xc0004c06c0, 0x199, 0xc0004b4a78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc00043e1e8 sp=0xc00043df58 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0004b4a50, 0x19ce1a0, 0xc0004c06c0, 0x199, 0xc0004c2900, 0x99)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00043e250 sp=0xc00043e1e8 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0004b4a50, 0x18bc100, 0xc0004b9ee0, 0x195, 0xc0004b4a78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00043e4e0 sp=0xc00043e250 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0004b4a50, 0x18bc100, 0xc0004b9ee0, 0x195, 0x18bc100, 0xc0004b9ee0)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00043e548 sp=0xc00043e4e0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0004b4a50, 0x1815520, 0xc0004b9d40, 0x16, 0xc0004b4a78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00043e7d8 sp=0xc00043e548 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0004b4a50, 0x1815520, 0xc0004b9d40, 0x16, 0xc00043e888, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00043e840 sp=0xc00043e7d8 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0004b4a50, 0x1815520, 0xc0004b9d40, 0xc0004b4a78, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00043e8c8 sp=0xc00043e840 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003da7b5, 0x9e1, 0xb64b, 0x1815520, 0xc0004b9d40, 0x26, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00043e910 sp=0xc00043e8c8 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc00040e000, 0xc0003da7b5, 0x9e1, 0xb64b, 0x7f25a5ef6680, 0xc00040e000)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc00043ec18 sp=0xc00043e910 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc00014ab00, 0x19ce1a0, 0xc00040e000, 0x199, 0xc00014ab28, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc00043eea8 sp=0xc00043ec18 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc00014ab00, 0x19ce1a0, 0xc00040e000, 0x199, 0xc0004b9b00, 0x99)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00043ef10 sp=0xc00043eea8 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc00014ab00, 0x18e59a0, 0xc000391f08, 0x195, 0xc00014ab28, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00043f1a0 sp=0xc00043ef10 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc00014ab00, 0x18e59a0, 0xc000391f08, 0x195, 0x18e59a0, 0xc000391f08)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00043f208 sp=0xc00043f1a0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc00014ab00, 0x1815520, 0xc000391d40, 0x16, 0xc00014ab28, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00043f498 sp=0xc00043f208 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc00014ab00, 0x1815520, 0xc000391d40, 0x16, 0xc000193548, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00043f500 sp=0xc00043f498 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc00014ab00, 0x1815520, 0xc000391d40, 0xc00014ab28, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00043f588 sp=0xc00043f500 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003d6000, 0x9d38, 0xfe00, 0x1815520, 0xc000391d40, 0x2aa0130, 0x7f25a5ef6500)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00043f5d0 sp=0xc00043f588 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc000391b00, 0xc0003d6000, 0x9d38, 0xfe00, 0x7f25a5ef6680, 0xc000391b00)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc00043f8d8 sp=0xc00043f5d0 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc00014aa50, 0x1a89300, 0xc000391b00, 0x16, 0xc00014aa78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc00043fb68 sp=0xc00043f8d8 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc00014aa50, 0x1a89300, 0xc000391b00, 0x16, 0xc000193c18, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00043fbd0 sp=0xc00043fb68 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc00014aa50, 0x1a89300, 0xc000391b00, 0xc00014aa78, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00043fc58 sp=0xc00043fbd0 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003d6000, 0x9d39, 0xfe00, 0x1a89300, 0xc000391b00, 0x0, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00043fca0 sp=0xc00043fc58 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.Swagger20Schema(0xc00038bb30, 0xc000193d68, 0x12e538a)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:82 +0xb8 fp=0xc00043fd08 sp=0xc00043fca0 pc=0x12e3bb8
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:66
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.initResolutionCache(0xc00038ba70, 0xc00038ba40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:57 +0x35 fp=0xc00043fd58 sp=0xc00043fd08 pc=0x12dedb5
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.init.0()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:51 +0x25 fp=0xc00043fd78 sp=0xc00043fd58 pc=0x12ded25
    runtime.doInit(0x288d900)
    	/usr/local/go/src/runtime/proc.go:5646 +0x8a fp=0xc00043fda8 sp=0xc00043fd78 pc=0x446f8a
    runtime.doInit(0x2884b40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043fdd8 sp=0xc00043fda8 pc=0x446f57
    runtime.doInit(0x2883340)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043fe08 sp=0xc00043fdd8 pc=0x446f57
    runtime.doInit(0x287fd40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043fe38 sp=0xc00043fe08 pc=0x446f57
    runtime.doInit(0x287c780)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043fe68 sp=0xc00043fe38 pc=0x446f57
    runtime.doInit(0x287c740)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043fe98 sp=0xc00043fe68 pc=0x446f57
    runtime.doInit(0x287c700)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043fec8 sp=0xc00043fe98 pc=0x446f57
    runtime.doInit(0x288ff40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043fef8 sp=0xc00043fec8 pc=0x446f57
    runtime.doInit(0x288c0e0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043ff28 sp=0xc00043fef8 pc=0x446f57
    runtime.doInit(0x28926a0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043ff58 sp=0xc00043ff28 pc=0x446f57
    runtime.doInit(0x2882980)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00043ff88 sp=0xc00043ff58 pc=0x446f57
    runtime.main()
    	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc00043ffe0 sp=0xc00043ff88 pc=0x439c05
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00043ffe8 sp=0xc00043ffe0 pc=0x46e061
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
