apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 9 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000089400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000089400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000055000, 0x8)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc00008aa80)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable]:
    compress/flate.(*decompressor).huffSym(0xc000367300, 0xc000367328, 0x5, 0x5, 0x0)
    	/usr/local/go/src/compress/flate/inflate.go:718 +0x18a
    compress/flate.(*decompressor).huffmanBlock(0xc000367300)
    	/usr/local/go/src/compress/flate/inflate.go:494 +0xd2
    compress/flate.(*decompressor).Read(0xc000367300, 0xc000a62000, 0xfe00, 0xfe00, 0x44d6f965, 0xc000a61e00, 0x200)
    	/usr/local/go/src/compress/flate/inflate.go:347 +0x79
    archive/zip.(*pooledFlateReader).Read(0xc000340120, 0xc000a62000, 0xfe00, 0xfe00, 0x0, 0x0, 0x0)
    	/usr/local/go/src/archive/zip/register.go:90 +0xb3
    archive/zip.(*checksumReader).Read(0xc0000a0410, 0xc000a62000, 0xfe00, 0xfe00, 0x200, 0x0, 0x0)
    	/usr/local/go/src/archive/zip/reader.go:194 +0x6c
    bytes.(*Buffer).ReadFrom(0xc00059b608, 0x7fb896c18100, 0xc0000a0410, 0x7fb896c18100, 0x1ceae00, 0x3e)
    	/usr/local/go/src/bytes/buffer.go:204 +0xb1
    io/ioutil.readAll(0x7fb896c18100, 0xc0000a0410, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/usr/local/go/src/io/ioutil/ioutil.go:36 +0xe5
    io/ioutil.ReadAll(...)
    	/usr/local/go/src/io/ioutil/ioutil.go:45
    k8s.io/kubernetes/vendor/github.com/chai2010/gettext-go/gettext.(*fileSystem).LoadMessagesFile(0xc000247380, 0x1ac3af3, 0x3, 0xc0006da8e8, 0x5, 0x1ac3820, 0x3, 0xc00040a840, 0xd, 0xc000850000, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/chai2010/gettext-go/gettext/fs.go:97 +0x553
    k8s.io/kubernetes/vendor/github.com/chai2010/gettext-go/gettext.(*domainManager).bindDomainTranslators(0xc0006325c0, 0x1ac3af3, 0x3, 0xc00040a830, 0xb, 0xc000844000, 0xc354, 0xf000)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/chai2010/gettext-go/gettext/domain_helper.go:19 +0x205
    k8s.io/kubernetes/vendor/github.com/chai2010/gettext-go/gettext.(*domainManager).Bind(0xc0006325c0, 0x1ac3af3, 0x3, 0xc00040a830, 0xb, 0xc000844000, 0xc354, 0xf000, 0x0, 0x0, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/chai2010/gettext-go/gettext/domain.go:37 +0x365
    k8s.io/kubernetes/vendor/github.com/chai2010/gettext-go/gettext.BindTextdomain(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/chai2010/gettext-go/gettext/gettext.go:55
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/i18n.LoadTranslations(0x1ac7ce3, 0x7, 0x0, 0x14, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/i18n/i18n.go:125 +0x6c8
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd.NewKubectlCommand(0x1ced9e0, 0xc00000e010, 0x1ceda00, 0xc00000e018, 0x1ceda00, 0xc00000e020, 0x46b3fb)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/cmd.go:500 +0x517
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd.NewDefaultKubectlCommandWithArgs(0x1cf8100, 0xc00030bc00, 0xc00003a080, 0x8, 0x8, 0x1ced9e0, 0xc00000e010, 0x1ceda00, 0xc00000e018, 0x1ceda00, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/cmd.go:307 +0x85
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd.NewDefaultKubectlCommand(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/cmd.go:302
    main.main()
    	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:38 +0x1ae
    
    goroutine 6 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
