apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    - hostname: staging-hackazon.kwaf-demo.tes*
      id: sample-hackazon
      path:
        operand: Prefix
        value: /
      protectionId: sample-hackazon-protection
    - hostname: staging-bwapp.kwaf-demo.tes*
      id: bwapp-sample
      path:
        operand: Prefix
        value: /
      protectionId: bwapp
    - hostname: staging-httpbin.kwaf-demo.tes*
      id: httpbin-sample
      path:
        operand: Prefix
        value: /
      protectionId: httpbin
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    - expressions:
        opMode: Active
      id: sample-hackazon-protection
      signatures:
        opMode: Active
    - expressions:
        opMode: Active
      id: httpbin
      signatures:
        opMode: Active
    - expressions:
        opMode: Active
      id: bwapp
      signatures:
        opMode: Active
