apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 4 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000062800)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000062800)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x0, 0xc000046000, 0x3)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0xc000046000, 0x2a6cc00)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.handoffp(0xc000046000)
    	/usr/local/go/src/runtime/proc.go:2001 +0x52
    runtime.stoplockedm()
    	/usr/local/go/src/runtime/proc.go:2075 +0xf7
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2611 +0x48c
    runtime.park_m(0xc000000180)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [chan receive, locked to thread]:
    runtime.gopark(0x1bb7a80, 0xc0000420c8, 0x170e, 0x2)
    	/usr/local/go/src/runtime/proc.go:306 +0xe5
    runtime.chanrecv(0xc000042070, 0x0, 0xc000000101, 0x41a55e)
    	/usr/local/go/src/runtime/chan.go:577 +0x36f
    runtime.chanrecv1(0xc000042070, 0x0)
    	/usr/local/go/src/runtime/chan.go:439 +0x2b
    runtime.gcenable()
    	/usr/local/go/src/runtime/mgc.go:219 +0x95
    runtime.main()
    	/usr/local/go/src/runtime/proc.go:167 +0x11e
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1
