apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    runtime: failed to create new OS thread (have 3 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x7b2d88, 0x9)
    	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
    runtime.newosproc(0xc000044380)
    	/usr/lib/go-1.13/src/runtime/os_linux.go:153 +0x1ba
    runtime.newm1(0xc000044380)
    	/usr/lib/go-1.13/src/runtime/proc.go:1853 +0xdc
    runtime.newm(0x7c71f0, 0xc000022500)
    	/usr/lib/go-1.13/src/runtime/proc.go:1832 +0x8f
    runtime.startm(0x0, 0xc000000601)
    	/usr/lib/go-1.13/src/runtime/proc.go:1969 +0x12a
    runtime.wakep(...)
    	/usr/lib/go-1.13/src/runtime/proc.go:2050
    runtime.newproc1(0x7c70d8, 0xc000040720, 0x0, 0xc000000180, 0x42f485)
    	/usr/lib/go-1.13/src/runtime/proc.go:3363 +0x319
    runtime.newproc.func1()
    	/usr/lib/go-1.13/src/runtime/proc.go:3256 +0x4f
    runtime.systemstack(0x457724)
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:370 +0x66
    runtime.mstart()
    	/usr/lib/go-1.13/src/runtime/proc.go:1146
    
    goroutine 1 [running, locked to thread]:
    runtime.systemstack_switch()
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:330 fp=0xc0000406c8 sp=0xc0000406c0 pc=0x457820
    runtime.newproc(0x0, 0x7c70d8)
    	/usr/lib/go-1.13/src/runtime/proc.go:3255 +0x6e fp=0xc000040710 sp=0xc0000406c8 pc=0x436c1e
    runtime.init.5()
    	/usr/lib/go-1.13/src/runtime/proc.go:242 +0x35 fp=0xc000040730 sp=0xc000040710 pc=0x42f485
    runtime.doInit(0xa2e260)
    	/usr/lib/go-1.13/src/runtime/proc.go:5222 +0x8a fp=0xc000040760 sp=0xc000040730 pc=0x43b34a
    runtime.main()
    	/usr/lib/go-1.13/src/runtime/proc.go:150 +0xc3 fp=0xc0000407e0 sp=0xc000040760 pc=0x42f173
    runtime.goexit()
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x459771
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    The connection to the server 10.100.0.139:6443 was refused - did you specify the right host or port?
