apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    system_key.go:147: cannot determine seccomp compiler version in generateSystemKey: fork/exec /snap/snapd/15534/usr/lib/snapd/snap-seccomp: resource temporarily unavailable
    runtime: failed to create new OS thread (have 2 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x7b2d88, 0x9)
    	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
    runtime.newosproc(0xc000044000)
    	/usr/lib/go-1.13/src/runtime/os_linux.go:153 +0x1ba
    runtime.newm1(0xc000044000)
    	/usr/lib/go-1.13/src/runtime/proc.go:1853 +0xdc
    runtime.newm(0x7c72e0, 0x0)
    	/usr/lib/go-1.13/src/runtime/proc.go:1832 +0x8f
    runtime.main.func1()
    	/usr/lib/go-1.13/src/runtime/proc.go:134 +0x36
    runtime.systemstack(0x457724)
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:370 +0x66
    runtime.mstart()
    	/usr/lib/go-1.13/src/runtime/proc.go:1146
    
    goroutine 1 [running]:
    runtime.systemstack_switch()
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:330 fp=0xc000040760 sp=0xc000040758 pc=0x457820
    runtime.main()
    	/usr/lib/go-1.13/src/runtime/proc.go:133 +0x63 fp=0xc0000407e0 sp=0xc000040760 pc=0x42f113
    runtime.goexit()
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x459771
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 9 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000063000)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000063000)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000055000, 0x8)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc000001080)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable, locked to thread]:
    regexp/syntax.(*compiler).cat(0xc0006dfc20, 0x7200000039, 0x13300000072, 0x16c00000267, 0x5f0000002d, 0x3a0000005f)
    	/usr/local/go/src/regexp/syntax/compile.go:188 +0x98
    regexp/syntax.(*compiler).compile(0xc0006dfc20, 0xc0006f1dc0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xc2c
    regexp/syntax.(*compiler).compile(0xc0006dfc20, 0xc0006f1e30, 0x7000000038, 0x6300000070)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc0006dfc20, 0xc0006f1ea0, 0x8, 0x8)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc0006dfc20, 0xc0006f1f10, 0x6e00000037, 0x650000006e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc0006dfc20, 0xc0006f1f80, 0xc0006df2e8, 0x2)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc0006dfc20, 0xc0006f2000, 0x6a00000035, 0x650000006a)
    	/usr/local/go/src/regexp/syntax/compile.go:128 +0x169c
    regexp/syntax.(*compiler).compile(0xc0006dfc20, 0xc0006f2070, 0x3400000065, 0x6800000068)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc0006dfc20, 0xc0006f20e0, 0x6800000001, 0xc000000068)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc0006dfc20, 0xc0006f2150, 0xc0006dfc58, 0x0)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.Compile(0xc0006f2150, 0xc0006f2150, 0x4, 0x4)
    	/usr/local/go/src/regexp/syntax/compile.go:73 +0x10c
    regexp.compile(0xc0001366e0, 0x151, 0xc0000000d4, 0xc0001367e2, 0xc0006dfdc8, 0xc0002f6690)
    	/usr/local/go/src/regexp/regexp.go:178 +0xdc
    regexp.Compile(...)
    	/usr/local/go/src/regexp/regexp.go:133
    regexp.MustCompile(0xc0001366e0, 0x151, 0x102)
    	/usr/local/go/src/regexp/regexp.go:309 +0x4b
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.expression(0xc000600020, 0x3, 0x3, 0xc0006603c0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:115 +0x93
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.anchored(0xc000600020, 0x3, 0x3, 0xc0006603c0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:142 +0x45
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.init()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:68 +0xdc6
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
