apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 10 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000063400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000063400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000057800, 0x9)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc00050a300)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable]:
    compress/flate.(*compressor).initDeflate(...)
    	/usr/local/go/src/compress/flate/deflate.go:372
    compress/flate.(*compressor).init(0xc000898000, 0x1cea8a0, 0xc000356e00, 0x5, 0x0, 0x0)
    	/usr/local/go/src/compress/flate/deflate.go:602 +0x5c5
    compress/flate.NewWriter(0x1cea8a0, 0xc000356e00, 0x5, 0x1858380, 0xc00076f87e, 0xc00076f880)
    	/usr/local/go/src/compress/flate/deflate.go:671 +0x65
    archive/zip.newFlateWriter(0x1cea8a0, 0xc000356e00, 0x1938201, 0x8000800356e00)
    	/usr/local/go/src/archive/zip/register.go:36 +0xea
    archive/zip.init.0.func2(0x1cea8a0, 0xc000356e00, 0x1bb4270, 0x0, 0xc00076f948, 0x7fd3e031d318)
    	/usr/local/go/src/archive/zip/register.go:112 +0x35
    archive/zip.(*Writer).CreateHeader(0xc00099fb18, 0xc00052b680, 0x2, 0x2, 0xc00068e300, 0x2d)
    	/usr/local/go/src/archive/zip/writer.go:359 +0x4fe
    archive/zip.(*Writer).Create(0xc00076fb18, 0xc000624500, 0x20, 0xc000624500, 0x20, 0xc00068e300, 0x2d)
    	/usr/local/go/src/archive/zip/writer.go:222 +0x69
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/i18n.LoadTranslations(0x1ac7ce3, 0x7, 0x0, 0x14, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/i18n/i18n.go:110 +0x4ed
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd.NewKubectlCommand(0x1ced9e0, 0xc00012a000, 0x1ceda00, 0xc00012a008, 0x1ceda00, 0xc00012a010, 0x46b3fb)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/cmd.go:500 +0x517
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd.NewDefaultKubectlCommandWithArgs(0x1cf8100, 0xc000356aa0, 0xc000130000, 0x8, 0x8, 0x1ced9e0, 0xc00012a000, 0x1ceda00, 0xc00012a008, 0x1ceda00, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/cmd.go:307 +0x85
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd.NewDefaultKubectlCommand(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/cmd.go:302
    main.main()
    	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:38 +0x1ae
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
