apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 9 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000500800)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000500800)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000055000, 0x8)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x2a6c401)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc000502300)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable, locked to thread]:
    regexp/syntax.nextRune(0xc0005bc048, 0x3b, 0x2, 0x2, 0x4, 0xc0005ae080, 0x2)
    	/usr/local/go/src/regexp/syntax/parse.go:1887 +0x125
    regexp/syntax.(*parser).parseClassChar(0xc0005460c0, 0xc0005bc048, 0x3b, 0xc0005bc041, 0x42, 0x4, 0x0, 0x0, 0x0, 0x0)
    	/usr/local/go/src/regexp/syntax/parse.go:1365 +0xa5
    regexp/syntax.(*parser).parseClass(0xc0005460c0, 0xc0005bc041, 0x42, 0xc0005bc041, 0x42, 0x0, 0x0)
    	/usr/local/go/src/regexp/syntax/parse.go:1586 +0x365
    regexp/syntax.Parse(0xc0005bc000, 0x83, 0xc0005b00d4, 0x83, 0xc0005bc000, 0x83)
    	/usr/local/go/src/regexp/syntax/parse.go:768 +0xceb
    regexp.compile(0xc0005bc000, 0x83, 0xc0000000d4, 0xc0005bc082, 0xc00070fdd0, 0xc00070fd98)
    	/usr/local/go/src/regexp/regexp.go:170 +0x5a
    regexp.Compile(...)
    	/usr/local/go/src/regexp/regexp.go:133
    regexp.MustCompile(0xc0005bc000, 0x83, 0x3)
    	/usr/local/go/src/regexp/regexp.go:309 +0x4b
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.group(0xc00070fe40, 0x1, 0x1, 0xc000302640)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:132 +0xbb
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.optional(0xc0003582a0, 0x2, 0x2, 0xc0003023c0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:121 +0x78
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.init()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:54 +0x791
    
    goroutine 6 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
