apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    system_key.go:147: cannot determine seccomp compiler version in generateSystemKey: fork/exec /snap/snapd/15534/usr/lib/snapd/snap-seccomp: resource temporarily unavailable
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 5 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    runtime: failed to create new OS thread (have 6 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc0002f2800)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc0002f2800)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x0, 0xc000046000, 0x4)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0xc000046000, 0x2a6cc00)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.handoffp(0xc000046000)
    	/usr/local/go/src/runtime/proc.go:2001 +0x52
    runtime.entersyscallblock_handoff()
    	/usr/local/go/src/runtime/proc.go:3213 +0x30
    runtime.systemstack(0x46c2f4)
    	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
    runtime.mstart()
    	/usr/local/go/src/runtime/proc.go:1116
    
    goroutine 1 [syscall, locked to thread]:
    runtime.notetsleepg(0x2a9eb78, 0xffffffffffffffff, 0xc000046000)
    	/usr/local/go/src/runtime/lock_futex.go:235 +0x34 fp=0xc000429fc8 sp=0xc000429f98 pc=0x40c454
    runtime.gcBgMarkStartWorkers()
    	/usr/local/go/src/runtime/mgc.go:1840 +0x90 fp=0xc00042a008 sp=0xc000429fc8 pc=0x41d150
    runtime.gcStart(0x0, 0x0, 0x0)
    	/usr/local/go/src/runtime/mgc.go:1296 +0x1ca fp=0xc00042a080 sp=0xc00042a008 pc=0x41bc2a
    runtime.mallocgc(0x240, 0x19ce1a0, 0x69303acf3a34c001, 0xc000499120)
    	/usr/local/go/src/runtime/malloc.go:1153 +0x470 fp=0xc00042a120 sp=0xc00042a080 pc=0x40da30
    runtime.newobject(...)
    	/usr/local/go/src/runtime/malloc.go:1195
    runtime.mapassign(0x18bc100, 0xc000481830, 0xc000499120, 0xc000499120)
    	/usr/local/go/src/runtime/map.go:667 +0x28b fp=0xc00042a1a0 sp=0xc00042a120 pc=0x40fd2b
    reflect.mapassign(0x18bc100, 0xc000481830, 0xc000499120, 0xc0004abb00)
    	/usr/local/go/src/runtime/map.go:1319 +0x3f fp=0xc00042a1d0 sp=0xc00042a1a0 pc=0x46795f
    reflect.Value.SetMapIndex(0x18bc100, 0xc0004ab3a0, 0x195, 0x1858200, 0xc000499120, 0x98, 0x19ce1a0, 0xc0004abb00, 0x199)
    	/usr/local/go/src/reflect/value.go:1706 +0x27c fp=0xc00042a250 sp=0xc00042a1d0 pc=0x4a08fc
    encoding/json.(*decodeState).object(0xc0004a29a0, 0x18bc100, 0xc0004ab3a0, 0x195, 0xc0004a29c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:807 +0x8da fp=0xc00042a4e0 sp=0xc00042a250 pc=0x6eb01a
    encoding/json.(*decodeState).value(0xc0004a29a0, 0x18bc100, 0xc0004ab3a0, 0x195, 0x18bc100, 0xc0004ab3a0)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00042a548 sp=0xc00042a4e0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0004a29a0, 0x1815520, 0xc0004ab200, 0x16, 0xc0004a29c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00042a7d8 sp=0xc00042a548 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0004a29a0, 0x1815520, 0xc0004ab200, 0x16, 0xc00042a888, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00042a840 sp=0xc00042a7d8 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0004a29a0, 0x1815520, 0xc0004ab200, 0xc0004a29c8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00042a8c8 sp=0xc00042a840 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003ca7b5, 0x9e1, 0xb64b, 0x1815520, 0xc0004ab200, 0x26, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00042a910 sp=0xc00042a8c8 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc0003fb440, 0xc0003ca7b5, 0x9e1, 0xb64b, 0x7f061023fb00, 0xc0003fb440)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc00042ac18 sp=0xc00042a910 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0000bea50, 0x19ce1a0, 0xc0003fb440, 0x199, 0xc0000bea78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc00042aea8 sp=0xc00042ac18 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0000bea50, 0x19ce1a0, 0xc0003fb440, 0x199, 0xc0004aafc0, 0x99)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00042af10 sp=0xc00042aea8 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0000bea50, 0x18e59a0, 0xc0003873c8, 0x195, 0xc0000bea78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00042b1a0 sp=0xc00042af10 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0000bea50, 0x18e59a0, 0xc0003873c8, 0x195, 0x18e59a0, 0xc0003873c8)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00042b208 sp=0xc00042b1a0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0000bea50, 0x1815520, 0xc000387200, 0x16, 0xc0000bea78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00042b498 sp=0xc00042b208 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0000bea50, 0x1815520, 0xc000387200, 0x16, 0xc0000fb548, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00042b500 sp=0xc00042b498 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0000bea50, 0x1815520, 0xc000387200, 0xc0000bea78, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00042b588 sp=0xc00042b500 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003c6000, 0x9d38, 0xfe00, 0x1815520, 0xc000387200, 0x7f06102e0788, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00042b5d0 sp=0xc00042b588 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc000386fc0, 0xc0003c6000, 0x9d38, 0xfe00, 0x7f061023fb00, 0xc000386fc0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc00042b8d8 sp=0xc00042b5d0 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0000be9a0, 0x1a89300, 0xc000386fc0, 0x16, 0xc0000be9c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc00042bb68 sp=0xc00042b8d8 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0000be9a0, 0x1a89300, 0xc000386fc0, 0x16, 0xc0000fbc18, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00042bbd0 sp=0xc00042bb68 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0000be9a0, 0x1a89300, 0xc000386fc0, 0xc0000be9c8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00042bc58 sp=0xc00042bbd0 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003c6000, 0x9d39, 0xfe00, 0x1a89300, 0xc000386fc0, 0x0, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00042bca0 sp=0xc00042bc58 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.Swagger20Schema(0xc000379b30, 0xc0000fbd68, 0x12e538a)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:82 +0xb8 fp=0xc00042bd08 sp=0xc00042bca0 pc=0x12e3bb8
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:66
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.initResolutionCache(0xc000379a70, 0xc000379a40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:57 +0x35 fp=0xc00042bd58 sp=0xc00042bd08 pc=0x12dedb5
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.init.0()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:51 +0x25 fp=0xc00042bd78 sp=0xc00042bd58 pc=0x12ded25
    runtime.doInit(0x288d900)
    	/usr/local/go/src/runtime/proc.go:5646 +0x8a fp=0xc00042bda8 sp=0xc00042bd78 pc=0x446f8a
    runtime.doInit(0x2884b40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042bdd8 sp=0xc00042bda8 pc=0x446f57
    runtime.doInit(0x2883340)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042be08 sp=0xc00042bdd8 pc=0x446f57
    runtime.doInit(0x287fd40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042be38 sp=0xc00042be08 pc=0x446f57
    runtime.doInit(0x287c780)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042be68 sp=0xc00042be38 pc=0x446f57
    runtime.doInit(0x287c740)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042be98 sp=0xc00042be68 pc=0x446f57
    runtime.doInit(0x287c700)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042bec8 sp=0xc00042be98 pc=0x446f57
    runtime.doInit(0x288ff40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042bef8 sp=0xc00042bec8 pc=0x446f57
    runtime.doInit(0x288c0e0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042bf28 sp=0xc00042bef8 pc=0x446f57
    runtime.doInit(0x28926a0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042bf58 sp=0xc00042bf28 pc=0x446f57
    runtime.doInit(0x2882980)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00042bf88 sp=0xc00042bf58 pc=0x446f57
    runtime.main()
    	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc00042bfe0 sp=0xc00042bf88 pc=0x439c05
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00042bfe8 sp=0xc00042bfe0 pc=0x46e061
    
    goroutine 6 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000108000)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000108000)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000048800, 0x5)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0xc000073f01)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc000001080)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    system_key.go:147: cannot determine seccomp compiler version in generateSystemKey: fork/exec /snap/snapd/15534/usr/lib/snapd/snap-seccomp: resource temporarily unavailable
