apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 7 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000100400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000100400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x0, 0xc00004b000, 0x6)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0xc00004b000, 0x2a6cc00)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.handoffp(0xc00004b000)
    	/usr/local/go/src/runtime/proc.go:2001 +0x52
    runtime.entersyscallblock_handoff()
    	/usr/local/go/src/runtime/proc.go:3213 +0x30
    runtime.systemstack(0x46c2f4)
    	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
    runtime.mstart()
    	/usr/local/go/src/runtime/proc.go:1116
    
    goroutine 1 [syscall, locked to thread]:
    runtime.notetsleepg(0x2a9eb78, 0xffffffffffffffff, 0xc000057800)
    	/usr/local/go/src/runtime/lock_futex.go:235 +0x34 fp=0xc00044dac8 sp=0xc00044da98 pc=0x40c454
    runtime.gcBgMarkStartWorkers()
    	/usr/local/go/src/runtime/mgc.go:1840 +0x90 fp=0xc00044db08 sp=0xc00044dac8 pc=0x41d150
    runtime.gcStart(0x0, 0x0, 0x0)
    	/usr/local/go/src/runtime/mgc.go:1296 +0x1ca fp=0xc00044db80 sp=0xc00044db08 pc=0x41bc2a
    runtime.mallocgc(0x240, 0x1926940, 0xc0000c3e01, 0x1bb7e20)
    	/usr/local/go/src/runtime/malloc.go:1153 +0x470 fp=0xc00044dc20 sp=0xc00044db80 pc=0x40da30
    runtime.newobject(0x1926940, 0xc0004a37d0)
    	/usr/local/go/src/runtime/malloc.go:1195 +0x38 fp=0xc00044dc50 sp=0xc00044dc20 pc=0x40e298
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc0004cdd40, 0xc0003f0879, 0xa1, 0xb587, 0x7f09d4e04400, 0xc0004cdd40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:551 +0x45 fp=0xc00044df58 sp=0xc00044dc50 pc=0x12e3305
    encoding/json.(*decodeState).object(0xc0004c69a0, 0x19ce1a0, 0xc0004cdd40, 0x199, 0xc0004c69c8, 0xc00044e27b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc00044e1e8 sp=0xc00044df58 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0004c69a0, 0x19ce1a0, 0xc0004cdd40, 0x199, 0xc0004cdd40, 0x199)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00044e250 sp=0xc00044e1e8 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0004c69a0, 0x18bc100, 0xc0004cd5e0, 0x195, 0xc0004c69c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00044e4e0 sp=0xc00044e250 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0004c69a0, 0x18bc100, 0xc0004cd5e0, 0x195, 0x18bc100, 0xc0004cd5e0)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00044e548 sp=0xc00044e4e0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0004c69a0, 0x1815520, 0xc0004cd440, 0x16, 0xc0004c69c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00044e7d8 sp=0xc00044e548 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0004c69a0, 0x1815520, 0xc0004cd440, 0x16, 0xc00044e888, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00044e840 sp=0xc00044e7d8 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0004c69a0, 0x1815520, 0xc0004cd440, 0xc0004c69c8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00044e8c8 sp=0xc00044e840 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003f07b5, 0x9e1, 0xb64b, 0x1815520, 0xc0004cd440, 0x26, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00044e910 sp=0xc00044e8c8 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc00041f680, 0xc0003f07b5, 0x9e1, 0xb64b, 0x7f09d4e04400, 0xc00041f680)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc00044ec18 sp=0xc00044e910 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0000e4a50, 0x19ce1a0, 0xc00041f680, 0x199, 0xc0000e4a78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc00044eea8 sp=0xc00044ec18 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0000e4a50, 0x19ce1a0, 0xc00041f680, 0x199, 0xc0004cd200, 0x99)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00044ef10 sp=0xc00044eea8 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0000e4a50, 0x18e59a0, 0xc0003ab608, 0x195, 0xc0000e4a78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00044f1a0 sp=0xc00044ef10 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0000e4a50, 0x18e59a0, 0xc0003ab608, 0x195, 0x18e59a0, 0xc0003ab608)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00044f208 sp=0xc00044f1a0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0000e4a50, 0x1815520, 0xc0003ab440, 0x16, 0xc0000e4a78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc00044f498 sp=0xc00044f208 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0000e4a50, 0x1815520, 0xc0003ab440, 0x16, 0xc0001a3548, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00044f500 sp=0xc00044f498 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0000e4a50, 0x1815520, 0xc0003ab440, 0xc0000e4a78, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00044f588 sp=0xc00044f500 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003ec000, 0x9d38, 0xfe00, 0x1815520, 0xc0003ab440, 0x7f09d4dfa3a8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00044f5d0 sp=0xc00044f588 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc0003ab200, 0xc0003ec000, 0x9d38, 0xfe00, 0x7f09d4e04400, 0xc0003ab200)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc00044f8d8 sp=0xc00044f5d0 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0000e49a0, 0x1a89300, 0xc0003ab200, 0x16, 0xc0000e49c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc00044fb68 sp=0xc00044f8d8 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0000e49a0, 0x1a89300, 0xc0003ab200, 0x16, 0xc0001a3c18, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc00044fbd0 sp=0xc00044fb68 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0000e49a0, 0x1a89300, 0xc0003ab200, 0xc0000e49c8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc00044fc58 sp=0xc00044fbd0 pc=0x6e87ca
    encoding/json.Unmarshal(0xc0003ec000, 0x9d39, 0xfe00, 0x1a89300, 0xc0003ab200, 0x0, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc00044fca0 sp=0xc00044fc58 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.Swagger20Schema(0xc00039db30, 0xc0001a3d68, 0x12e538a)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:82 +0xb8 fp=0xc00044fd08 sp=0xc00044fca0 pc=0x12e3bb8
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:66
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.initResolutionCache(0xc00039da70, 0xc00039da40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:57 +0x35 fp=0xc00044fd58 sp=0xc00044fd08 pc=0x12dedb5
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.init.0()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:51 +0x25 fp=0xc00044fd78 sp=0xc00044fd58 pc=0x12ded25
    runtime.doInit(0x288d900)
    	/usr/local/go/src/runtime/proc.go:5646 +0x8a fp=0xc00044fda8 sp=0xc00044fd78 pc=0x446f8a
    runtime.doInit(0x2884b40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044fdd8 sp=0xc00044fda8 pc=0x446f57
    runtime.doInit(0x2883340)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044fe08 sp=0xc00044fdd8 pc=0x446f57
    runtime.doInit(0x287fd40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044fe38 sp=0xc00044fe08 pc=0x446f57
    runtime.doInit(0x287c780)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044fe68 sp=0xc00044fe38 pc=0x446f57
    runtime.doInit(0x287c740)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044fe98 sp=0xc00044fe68 pc=0x446f57
    runtime.doInit(0x287c700)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044fec8 sp=0xc00044fe98 pc=0x446f57
    runtime.doInit(0x288ff40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044fef8 sp=0xc00044fec8 pc=0x446f57
    runtime.doInit(0x288c0e0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044ff28 sp=0xc00044fef8 pc=0x446f57
    runtime.doInit(0x28926a0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044ff58 sp=0xc00044ff28 pc=0x446f57
    runtime.doInit(0x2882980)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc00044ff88 sp=0xc00044ff58 pc=0x446f57
    runtime.main()
    	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc00044ffe0 sp=0xc00044ff88 pc=0x439c05
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00044ffe8 sp=0xc00044ffe0 pc=0x46e061
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
