apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 10 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000500400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000500400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000057800, 0x9)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc0004d0180)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable, locked to thread]:
    bytes.makeSlice.func1()
    	/usr/local/go/src/bytes/buffer.go:224 +0x6b
    bytes.makeSlice(0xc5, 0xc000138000, 0xc5, 0xc5)
    	/usr/local/go/src/bytes/buffer.go:229 +0x96
    bytes.(*Buffer).grow(0xc000600090, 0x45, 0x1)
    	/usr/local/go/src/bytes/buffer.go:142 +0x156
    bytes.(*Buffer).WriteString(0xc000600090, 0xc0006101e0, 0x45, 0x1, 0x0, 0x0)
    	/usr/local/go/src/bytes/buffer.go:184 +0xd0
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/templates.(*ASCIIRenderer).NormalText(0xc000200200, 0xc000600090, 0xc000136000, 0x45, 0x310)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/templates/markdown.go:52 +0x116
    k8s.io/kubernetes/vendor/github.com/russross/blackfriday.(*parser).inline(0xc000130000, 0xc000600090, 0xc000136000, 0x45, 0x310)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/russross/blackfriday/inline.go:46 +0xda
    k8s.io/kubernetes/vendor/github.com/russross/blackfriday.(*parser).renderParagraph.func1(0xc000600090)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/russross/blackfriday/block.go:1332 +0x79
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/templates.(*ASCIIRenderer).Paragraph(0xc000200200, 0xc000600090, 0xc000338080)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/templates/markdown.go:86 +0x4f
    k8s.io/kubernetes/vendor/github.com/russross/blackfriday.(*parser).renderParagraph(0xc000130000, 0xc000600090, 0xc000136000, 0x46, 0x310)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/russross/blackfriday/block.go:1335 +0x118
    k8s.io/kubernetes/vendor/github.com/russross/blackfriday.(*parser).paragraph(0xc000130000, 0xc000600090, 0xc000136000, 0x200, 0x310, 0x40e298)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/russross/blackfriday/block.go:1360 +0x9cf
    k8s.io/kubernetes/vendor/github.com/russross/blackfriday.(*parser).block(0xc000130000, 0xc000600090, 0xc000136000, 0x200, 0x310)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/russross/blackfriday/block.go:186 +0x3d4
    k8s.io/kubernetes/vendor/github.com/russross/blackfriday.secondPass(0xc000130000, 0xc000136000, 0x200, 0x310, 0xc000136000, 0x200, 0x310)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/russross/blackfriday/markdown.go:459 +0x87
    k8s.io/kubernetes/vendor/github.com/russross/blackfriday.MarkdownOptions(0xc00012e200, 0x1ff, 0x200, 0x1d4e100, 0xc000200200, 0x1, 0x0, 0xa, 0xa, 0x1b843cf)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/russross/blackfriday/markdown.go:389 +0x1e5
    k8s.io/kubernetes/vendor/github.com/russross/blackfriday.Markdown(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/russross/blackfriday/markdown.go:343
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/templates.normalizer.markdown(0xc00012e000, 0x1ff, 0xc00012e000, 0x1ff)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/templates/normalizers.go:73 +0xcf
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/templates.LongDesc(0x1b843cf, 0x20e, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/templates/normalizers.go:34 +0x6f
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait.init()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait/wait.go:49 +0x65
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
