apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 10 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000063000)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000063000)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000057800, 0x9)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc000500000)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable, locked to thread]:
    regexp/syntax.(*compiler).quest(0xc00073fc20, 0x14f00000059, 0x10000000100, 0x100, 0x8a00d4)
    	/usr/local/go/src/regexp/syntax/compile.go:217 +0x22b
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185a40, 0xb000000058, 0xb0)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xf25
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185ab0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185b20, 0xae00000057, 0xae)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185b90, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185c00, 0xac00000056, 0xac)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185c70, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185ce0, 0xaa00000055, 0xaa)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185d50, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185dc0, 0xa800000054, 0xa8)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185e30, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185ea0, 0xa600000053, 0xa6)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185f10, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000185f80, 0xa400000052, 0xa4)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188000, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188070, 0xa200000051, 0xa2)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001880e0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188150, 0xa000000050, 0xa0)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001881c0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188230, 0x9e0000004f, 0x9e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001882a0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188310, 0x9c0000004e, 0x9c)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188380, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001883f0, 0x9a0000004d, 0x9a)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188460, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001884d0, 0x980000004c, 0x98)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188540, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001885b0, 0x960000004b, 0x96)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188620, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188690, 0x940000004a, 0x94)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188700, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188770, 0x9200000049, 0x92)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001887e0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188850, 0x9000000048, 0x90)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001888c0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188930, 0x8e00000047, 0x8e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001889a0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188a10, 0x8c00000046, 0x202020200000008c)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188a80, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188af0, 0x8a00000045, 0x8a)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188b60, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188bd0, 0x8800000044, 0x20300000000088)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188c40, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188cb0, 0x8600000043, 0x86)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188d20, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188d90, 0x8400000042, 0x84)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188e00, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188e70, 0x8200000041, 0x82)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188ee0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188f50, 0x8000000040, 0x22202c2200000080)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000188fc0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189030, 0x7e0000003f, 0x202020200000007e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001890a0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189110, 0x7c0000003e, 0x202020200000007c)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189180, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001891f0, 0x7a0000003d, 0x7a)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189260, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001892d0, 0x780000003c, 0x78)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189340, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001893b0, 0x760000003b, 0x76)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189420, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189490, 0x740000003a, 0x74)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189500, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189570, 0x7200000039, 0x72)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001895e0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189650, 0x7000000038, 0x70)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001896c0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189730, 0x6e00000037, 0x6e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001897a0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189810, 0x6c00000036, 0x6c)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189880, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001898f0, 0x6a00000035, 0x6a)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189960, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc0001899d0, 0x6800000034, 0x68)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189a40, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189ab0, 0x6600000033, 0xc000000066)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189b20, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189b90, 0x6400000032, 0x64)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189c00, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189c70, 0x6200000031, 0xc000000062)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189ce0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189d50, 0x6000000030, 0x60)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189dc0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189e30, 0x5e0000002f, 0x5e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189ea0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189f10, 0x5c0000002e, 0x5c)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc000189f80, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a000, 0x5a0000002d, 0x5a)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a070, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a0e0, 0x580000002c, 0x58)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a150, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a1c0, 0x560000002b, 0x56)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a230, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a2a0, 0x540000002a, 0x54)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a310, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a380, 0x5200000029, 0x52)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a3f0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a460, 0x5000000028, 0xc000000050)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a4d0, 0xa, 0x10)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.(*compiler).compile(0xc00073fc20, 0xc00019a540, 0x4e00000027, 0x4e)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    ...additional frames elided...
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
