apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    runtime: failed to create new OS thread (have 5 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x7b2d88, 0x9)
    	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72
    runtime.newosproc(0xc00006a000)
    	/usr/lib/go-1.13/src/runtime/os_linux.go:153 +0x1ba
    runtime.newm1(0xc00006a000)
    	/usr/lib/go-1.13/src/runtime/proc.go:1853 +0xdc
    runtime.newm(0x7c71f0, 0xc000024a00)
    	/usr/lib/go-1.13/src/runtime/proc.go:1832 +0x8f
    runtime.startm(0x0, 0xc000000101)
    	/usr/lib/go-1.13/src/runtime/proc.go:1969 +0x12a
    runtime.wakep(...)
    	/usr/lib/go-1.13/src/runtime/proc.go:2050
    runtime.resetspinning()
    	/usr/lib/go-1.13/src/runtime/proc.go:2430 +0x93
    runtime.schedule()
    	/usr/lib/go-1.13/src/runtime/proc.go:2531 +0x2a0
    runtime.mstart1()
    	/usr/lib/go-1.13/src/runtime/proc.go:1208 +0x8e
    runtime.mstart()
    	/usr/lib/go-1.13/src/runtime/proc.go:1167 +0x6e
    
    goroutine 1 [runnable, locked to thread]:
    runtime.chanrecv(0xc000060000, 0x0, 0xc000000101, 0x418fde)
    	/usr/lib/go-1.13/src/runtime/chan.go:421 +0x6a9
    runtime.chanrecv1(0xc000060000, 0x0)
    	/usr/lib/go-1.13/src/runtime/chan.go:406 +0x2b
    runtime.gcenable()
    	/usr/lib/go-1.13/src/runtime/mgc.go:212 +0x95
    runtime.main()
    	/usr/lib/go-1.13/src/runtime/proc.go:166 +0x121
    runtime.goexit()
    	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    - expressions:
        opMode: Active
      id: hackazon
      signatures:
        opMode: Active
      whitelist:
        opMode: Bypass
    - expressions:
        opMode: Active
      id: httpbin
      signatures:
        opMode: Active
      whitelist:
        opMode: Bypass
    - expressions:
        opMode: Active
      id: bwapp
      signatures:
        opMode: Active
      whitelist:
        opMode: Bypass
    - expressions:
        opMode: Active
      id: nginx
      signatures:
        opMode: Active
      whitelist:
        opMode: Bypass
