apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 10 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000580400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000580400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000057800, 0x9)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0xc000119f01)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc000502000)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable, locked to thread]:
    sync.(*Map).Load(0x2a6b508, 0x18583c0, 0xc00089f450, 0x1, 0x538e732e, 0x1)
    	/usr/local/go/src/sync/map.go:102 +0x30a
    reflect.FuncOf(0xc00040c5c0, 0x2, 0x2, 0x2a9d9d0, 0x0, 0x0, 0xc000325900, 0x0, 0x0)
    	/usr/local/go/src/reflect/type.go:2003 +0x49c
    reflect.(*rtype).Method(0x1aa99c0, 0x1, 0x179638b, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/usr/local/go/src/reflect/type.go:824 +0x50b
    reflect.(*rtype).MethodByName(0x1aa99c0, 0x1acde06, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/usr/local/go/src/reflect/type.go:846 +0x1d8
    reflect.Value.MethodByName(0x1aa99c0, 0xc000684140, 0x16, 0x1acde06, 0xc, 0xc000788c30, 0x0, 0x1)
    	/usr/local/go/src/reflect/value.go:1359 +0x7e
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0xc0004a1b90, 0x1ad61dd, 0x11, 0x1ac99c5, 0x8, 0x17bbaca, 0xd, 0x1cf6240, 0xc000684140)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:212 +0x6b1
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0xc0004a1b90, 0x1ad61dd, 0x11, 0x1ac99c5, 0x8, 0xc00089fbb0, 0x2, 0x2)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:176 +0x25a
    k8s.io/kubernetes/vendor/k8s.io/api/scheduling/v1alpha1.addKnownTypes(0xc0004a1b90, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/api/scheduling/v1alpha1/register.go:46 +0xde
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(0x2a63d50, 0xc0004a1b90, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/scheme_builder.go:29 +0x6d
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(0x2a4b870, 0xc0004a1b90, 0x17cd9d9, 0x19)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/scheme_builder.go:29 +0x6d
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/scheme.init.0()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/scheme/install.go:64 +0x32c
    
    goroutine 6 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
