apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 9 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc00060a400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc00060a400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x0, 0xc000050000, 0x8)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0xc000050000, 0x2a6cc00)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.handoffp(0xc000050000)
    	/usr/local/go/src/runtime/proc.go:2001 +0x52
    runtime.entersyscallblock_handoff()
    	/usr/local/go/src/runtime/proc.go:3213 +0x30
    runtime.systemstack(0x46c2f4)
    	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
    runtime.mstart()
    	/usr/local/go/src/runtime/proc.go:1116
    
    goroutine 1 [syscall, locked to thread]:
    runtime.notetsleepg(0x2a9eb78, 0xffffffffffffffff, 0xc000052800)
    	/usr/local/go/src/runtime/lock_futex.go:235 +0x34 fp=0xc00049ffc8 sp=0xc00049ff98 pc=0x40c454
    runtime.gcBgMarkStartWorkers()
    	/usr/local/go/src/runtime/mgc.go:1840 +0x90 fp=0xc0004a0008 sp=0xc00049ffc8 pc=0x41d150
    runtime.gcStart(0x0, 0x0, 0x0)
    	/usr/local/go/src/runtime/mgc.go:1296 +0x1ca fp=0xc0004a0080 sp=0xc0004a0008 pc=0x41bc2a
    runtime.mallocgc(0x240, 0x19ce1a0, 0x368bfc2a0a8c1701, 0xc00050b1c0)
    	/usr/local/go/src/runtime/malloc.go:1153 +0x470 fp=0xc0004a0120 sp=0xc0004a0080 pc=0x40da30
    runtime.newobject(...)
    	/usr/local/go/src/runtime/malloc.go:1195
    runtime.mapassign(0x18bc100, 0xc0004f3830, 0xc00050b1c0, 0xc00050b1c0)
    	/usr/local/go/src/runtime/map.go:667 +0x28b fp=0xc0004a01a0 sp=0xc0004a0120 pc=0x40fd2b
    reflect.mapassign(0x18bc100, 0xc0004f3830, 0xc00050b1c0, 0xc000522d80)
    	/usr/local/go/src/runtime/map.go:1319 +0x3f fp=0xc0004a01d0 sp=0xc0004a01a0 pc=0x46795f
    reflect.Value.SetMapIndex(0x18bc100, 0xc000522620, 0x195, 0x1858200, 0xc00050b1c0, 0x98, 0x19ce1a0, 0xc000522d80, 0x199)
    	/usr/local/go/src/reflect/value.go:1706 +0x27c fp=0xc0004a0250 sp=0xc0004a01d0 pc=0x4a08fc
    encoding/json.(*decodeState).object(0xc0005169a0, 0x18bc100, 0xc000522620, 0x195, 0xc0005169c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:807 +0x8da fp=0xc0004a04e0 sp=0xc0004a0250 pc=0x6eb01a
    encoding/json.(*decodeState).value(0xc0005169a0, 0x18bc100, 0xc000522620, 0x195, 0x18bc100, 0xc000522620)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc0004a0548 sp=0xc0004a04e0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc0005169a0, 0x1815520, 0xc000522480, 0x16, 0xc0005169c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc0004a07d8 sp=0xc0004a0548 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc0005169a0, 0x1815520, 0xc000522480, 0x16, 0xc0004a0888, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc0004a0840 sp=0xc0004a07d8 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0005169a0, 0x1815520, 0xc000522480, 0xc0005169c8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc0004a08c8 sp=0xc0004a0840 pc=0x6e87ca
    encoding/json.Unmarshal(0xc00043c7b5, 0x9e1, 0xb64b, 0x1815520, 0xc000522480, 0x26, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc0004a0910 sp=0xc0004a08c8 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc00046e6c0, 0xc00043c7b5, 0x9e1, 0xb64b, 0x7f9b5eed0b00, 0xc00046e6c0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc0004a0c18 sp=0xc0004a0910 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc000136a50, 0x19ce1a0, 0xc00046e6c0, 0x199, 0xc000136a78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc0004a0ea8 sp=0xc0004a0c18 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc000136a50, 0x19ce1a0, 0xc00046e6c0, 0x199, 0xc000522240, 0x99)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc0004a0f10 sp=0xc0004a0ea8 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc000136a50, 0x18e59a0, 0xc00041c648, 0x195, 0xc000136a78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc0004a11a0 sp=0xc0004a0f10 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc000136a50, 0x18e59a0, 0xc00041c648, 0x195, 0x18e59a0, 0xc00041c648)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc0004a1208 sp=0xc0004a11a0 pc=0x6e904d
    encoding/json.(*decodeState).object(0xc000136a50, 0x1815520, 0xc00041c480, 0x16, 0xc000136a78, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:765 +0x12fe fp=0xc0004a1498 sp=0xc0004a1208 pc=0x6eba3e
    encoding/json.(*decodeState).value(0xc000136a50, 0x1815520, 0xc00041c480, 0x16, 0xc000173548, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc0004a1500 sp=0xc0004a1498 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc000136a50, 0x1815520, 0xc00041c480, 0xc000136a78, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc0004a1588 sp=0xc0004a1500 pc=0x6e87ca
    encoding/json.Unmarshal(0xc000438000, 0x9d38, 0xfe00, 0x1815520, 0xc00041c480, 0x7f9b5eec8728, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc0004a15d0 sp=0xc0004a1588 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc00041c240, 0xc000438000, 0x9d38, 0xfe00, 0x7f9b5eed0b00, 0xc00041c240)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x8b fp=0xc0004a18d8 sp=0xc0004a15d0 pc=0x12e334b
    encoding/json.(*decodeState).object(0xc0001369a0, 0x1a89300, 0xc00041c240, 0x16, 0xc0001369c8, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:609 +0x207c fp=0xc0004a1b68 sp=0xc0004a18d8 pc=0x6ec7bc
    encoding/json.(*decodeState).value(0xc0001369a0, 0x1a89300, 0xc00041c240, 0x16, 0xc000173c18, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d fp=0xc0004a1bd0 sp=0xc0004a1b68 pc=0x6e904d
    encoding/json.(*decodeState).unmarshal(0xc0001369a0, 0x1a89300, 0xc00041c240, 0xc0001369c8, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea fp=0xc0004a1c58 sp=0xc0004a1bd0 pc=0x6e87ca
    encoding/json.Unmarshal(0xc000438000, 0x9d39, 0xfe00, 0x1a89300, 0xc00041c240, 0x0, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112 fp=0xc0004a1ca0 sp=0xc0004a1c58 pc=0x6e8172
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.Swagger20Schema(0xc0003ebb30, 0xc000173d68, 0x12e538a)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:82 +0xb8 fp=0xc0004a1d08 sp=0xc0004a1ca0 pc=0x12e3bb8
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:66
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.initResolutionCache(0xc0003eba70, 0xc0003eba40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:57 +0x35 fp=0xc0004a1d58 sp=0xc0004a1d08 pc=0x12dedb5
    k8s.io/kubernetes/vendor/github.com/go-openapi/spec.init.0()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:51 +0x25 fp=0xc0004a1d78 sp=0xc0004a1d58 pc=0x12ded25
    runtime.doInit(0x288d900)
    	/usr/local/go/src/runtime/proc.go:5646 +0x8a fp=0xc0004a1da8 sp=0xc0004a1d78 pc=0x446f8a
    runtime.doInit(0x2884b40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1dd8 sp=0xc0004a1da8 pc=0x446f57
    runtime.doInit(0x2883340)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1e08 sp=0xc0004a1dd8 pc=0x446f57
    runtime.doInit(0x287fd40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1e38 sp=0xc0004a1e08 pc=0x446f57
    runtime.doInit(0x287c780)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1e68 sp=0xc0004a1e38 pc=0x446f57
    runtime.doInit(0x287c740)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1e98 sp=0xc0004a1e68 pc=0x446f57
    runtime.doInit(0x287c700)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1ec8 sp=0xc0004a1e98 pc=0x446f57
    runtime.doInit(0x288ff40)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1ef8 sp=0xc0004a1ec8 pc=0x446f57
    runtime.doInit(0x288c0e0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1f28 sp=0xc0004a1ef8 pc=0x446f57
    runtime.doInit(0x28926a0)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1f58 sp=0xc0004a1f28 pc=0x446f57
    runtime.doInit(0x2882980)
    	/usr/local/go/src/runtime/proc.go:5641 +0x57 fp=0xc0004a1f88 sp=0xc0004a1f58 pc=0x446f57
    runtime.main()
    	/usr/local/go/src/runtime/proc.go:191 +0x1c5 fp=0xc0004a1fe0 sp=0xc0004a1f88 pc=0x439c05
    runtime.goexit()
    	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0004a1fe8 sp=0xc0004a1fe0 pc=0x46e061
    
    goroutine 6 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
