apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 9 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000508400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000508400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000055000, 0x8)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0xc000542001)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc00050a900)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable]:
    encoding/json.(*decodeState).scanWhile(0xc0001d7810, 0x9)
    	/usr/local/go/src/encoding/json/decode.go:288 +0xf3
    encoding/json.(*decodeState).object(0xc0001d7810, 0x18151e0, 0xc00000d6a0, 0x16, 0xc0001d7838, 0x7b)
    	/usr/local/go/src/encoding/json/decode.go:664 +0x318
    encoding/json.(*decodeState).value(0xc0001d7810, 0x18151e0, 0xc00000d6a0, 0x16, 0xc0004ceee0, 0x6fa8ab)
    	/usr/local/go/src/encoding/json/decode.go:370 +0x6d
    encoding/json.(*decodeState).unmarshal(0xc0001d7810, 0x18151e0, 0xc00000d6a0, 0xc0001d7838, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:180 +0x1ea
    encoding/json.Unmarshal(0xc0006aa800, 0x15c2, 0x1800, 0x18151e0, 0xc00000d6a0, 0xc0006aa800, 0x0)
    	/usr/local/go/src/encoding/json/decode.go:107 +0x112
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.SimpleMetaFactory.Interpret(0xc0006aa800, 0x15c2, 0x1800, 0x0, 0x0, 0xc000269200)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/meta.go:55 +0x77
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode(0xc000338190, 0xc0006a9000, 0x15a8, 0x17a8, 0xc00042ecf0, 0x1cf7bc0, 0xc0003b2060, 0x1, 0x7f561818f7d0, 0x7f55f1516310, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:219 +0x96
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode(0xc0003b03c0, 0xc0006a9000, 0x15a8, 0x17a8, 0xc00042ecf0, 0x1cf7bc0, 0xc0003b2060, 0xc000416658, 0x0, 0x0, ...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:136 +0xa9
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.Load(0xc0006a9000, 0x15a8, 0x17a8, 0x15a8, 0x17a8, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:416 +0x1aa
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.LoadFromFile(0xc0004534c0, 0x1a, 0x1, 0xc0002691c0, 0x1)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:375 +0x85
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*ClientConfigLoadingRules).Load(0xc000101590, 0xc00042ebd0, 0x30, 0x7f55f1501390)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:205 +0xb8f
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).createClientConfig(0xc0001015e0, 0x0, 0x0, 0x0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:69 +0xba
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.(*DeferredLoadingClientConfig).Namespace(0xc0001015e0, 0xc0004cfbb0, 0x14ff493, 0xc0001d6a50, 0x1d29f00, 0xc0002691e0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/merged_client_builder.go:131 +0x45
    k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions.(*clientConfig).Namespace(0xc0002691e0, 0x1d29f00, 0xc0002691e0, 0x32, 0x2a9f4a0, 0x0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/client_config.go:61 +0x37
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.(*GetOptions).Complete(0xc0007a8b40, 0x1d441c0, 0xc000301f50, 0xc00045c2c0, 0xc00063bf20, 0x2, 0x6, 0x6e5000, 0xc0004cfcf8)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:199 +0xe8
    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func1(0xc00045c2c0, 0xc00063bf20, 0x2, 0x6)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:165 +0x7d
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00045c2c0, 0xc00063bec0, 0x6, 0x6, 0xc00045c2c0, 0xc00063bec0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000156b00, 0xc000120180, 0xc000130000, 0x8)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
    main.main()
    	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
    
    goroutine 37 [select]:
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1bb7018, 0x1cec100, 0xc000542000, 0x1, 0xc000102b40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1bb7018, 0x12a05f200, 0x0, 0x1, 0xc000102b40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1bb7018, 0x12a05f200, 0xc000102b40)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
    created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96
