apiVersion: waas.radware.com/v1beta1
kind: Profile
metadata:
  name:  waas-api-profile
  namespace: kwaf
  labels:
    release: waas
spec:
  policies:
  - classifiers:
    Error: bad file '-': yaml: line 11: mapping values are not allowed in this context
    name: apiPolicy
    operatorEmail: support@radware.com
    protections:
    runtime: failed to create new OS thread (have 10 already; errno=11)
    runtime: may need to increase max user processes (ulimit -u)
    fatal error: newosproc
    
    runtime stack:
    runtime.throw(0x1acaa5a, 0x9)
    	/usr/local/go/src/runtime/panic.go:1116 +0x72
    runtime.newosproc(0xc000590400)
    	/usr/local/go/src/runtime/os_linux.go:161 +0x1c5
    runtime.newm1(0xc000590400)
    	/usr/local/go/src/runtime/proc.go:1837 +0xdd
    runtime.newm(0x1bb7c48, 0xc000055000, 0x9)
    	/usr/local/go/src/runtime/proc.go:1816 +0x9b
    runtime.startm(0x0, 0x426301)
    	/usr/local/go/src/runtime/proc.go:1973 +0xc9
    runtime.wakep()
    	/usr/local/go/src/runtime/proc.go:2061 +0x66
    runtime.resetspinning()
    	/usr/local/go/src/runtime/proc.go:2533 +0x59
    runtime.schedule()
    	/usr/local/go/src/runtime/proc.go:2684 +0x2b9
    runtime.park_m(0xc00018a480)
    	/usr/local/go/src/runtime/proc.go:2845 +0x9d
    runtime.mcall(0x0)
    	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b
    
    goroutine 1 [runnable, locked to thread]:
    unicode.SimpleFold(0x2d, 0xc00055c140)
    	/usr/local/go/src/unicode/letter.go:336 +0x156
    regexp/syntax.(*compiler).rune(0xc00076fbc8, 0xc0005597e0, 0x1, 0x2, 0xc0005100d4, 0x7, 0x0)
    	/usr/local/go/src/regexp/syntax/compile.go:261 +0x1ca
    regexp/syntax.(*compiler).compile(0xc00078fbc8, 0xc0005597a0, 0x60000000a, 0xc0000000c)
    	/usr/local/go/src/regexp/syntax/compile.go:100 +0x148
    regexp/syntax.(*compiler).compile(0xc00078fbc8, 0xc000559810, 0x500000008, 0xc0000000c)
    	/usr/local/go/src/regexp/syntax/compile.go:132 +0xf94
    regexp/syntax.(*compiler).compile(0xc00078fbc8, 0xc000559880, 0xc00048f8f0, 0x0)
    	/usr/local/go/src/regexp/syntax/compile.go:153 +0xe25
    regexp/syntax.(*compiler).compile(0xc00078fbc8, 0xc0005599d0, 0x4, 0x4)
    	/usr/local/go/src/regexp/syntax/compile.go:144 +0xbbb
    regexp/syntax.(*compiler).compile(0xc00078fbc8, 0xc000559a40, 0x4, 0x700000003)
    	/usr/local/go/src/regexp/syntax/compile.go:134 +0x102e
    regexp/syntax.(*compiler).compile(0xc00078fbc8, 0xc000559ab0, 0x200000002, 0x700000007)
    	/usr/local/go/src/regexp/syntax/compile.go:136 +0xee6
    regexp/syntax.(*compiler).compile(0xc00078fbc8, 0xc000559b20, 0xc00076fc00, 0x0)
    	/usr/local/go/src/regexp/syntax/compile.go:146 +0xbeb
    regexp/syntax.Compile(0xc000559b20, 0xc000559b20, 0x1, 0x1)
    	/usr/local/go/src/regexp/syntax/compile.go:73 +0x10c
    regexp.compile(0xc0001b34d0, 0x2d, 0xd4, 0x1, 0x2, 0xc0001b34d0)
    	/usr/local/go/src/regexp/regexp.go:178 +0xdc
    regexp.Compile(...)
    	/usr/local/go/src/regexp/regexp.go:133
    regexp.MustCompile(0xc0001b34d0, 0x2d, 0x0)
    	/usr/local/go/src/regexp/regexp.go:309 +0x4b
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.expression(0xc00076fe40, 0x1, 0x1, 0x2d)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:115 +0x93
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.group(0xc00076fe40, 0x1, 0x1, 0xc00055a320)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:132 +0x45
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.repeated(0xc00044d040, 0x2, 0x2, 0xc00055a0a0)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:127 +0x78
    k8s.io/kubernetes/vendor/github.com/docker/distribution/reference.init()
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/distribution/reference/regexp.go:63 +0xa65
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2a6c040)
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
    	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf
