apiVersion: v1
kind: Service
metadata:
  name: sample-hackazon-service
  namespace: test
spec:
  selector:
    app: hackazon
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-hackazon-deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app: hackazon
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      containers:
        - name: sample-hackazon
          image: sambercovici/hackazon
          imagePullPolicy: IfNotPresent
          readinessProbe:
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /
              port: 80
              scheme: HTTP
          livenessProbe:
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /
              port: 80
              scheme: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: hackazon-gateway
  namespace: test
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "hackazon.kwaf-demo.test"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hackazon
  namespace: test
spec:
  hosts:
  - "hackazon.kwaf-demo.test"
  gateways:
  - hackazon-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: sample-hackazon-service.test.svc.cluster.local
